import { guides, routePlaceholders, allDefaultChecklistItems, siteMeta } from './content.js';
import { createStore, hasLegacyData } from './db.js';

const $=(s,r=document)=>r.querySelector(s); const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const slug=v=>(v||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const fmt=iso=>iso?new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(new Date(iso)):'';

document.documentElement.style.setProperty('--gr1d-skin',`url('./assets/gr1d-skin.png')`);
document.documentElement.style.setProperty('--benamu-skin',`url('./assets/benamu-skin.png')`);

const app=$('#app'),actorSelect=$('#actor-select'),syncStatus=$('#sync-status'),dbBanner=$('#db-banner'),itemDialog=$('#item-dialog'),confirmDialog=$('#confirm-dialog'),migrationDialog=$('#migration-dialog'),searchDialog=$('#search-dialog'),searchInput=$('#global-search'),searchResults=$('#search-results'),toastRegion=$('#toast-region');
const reduced=matchMedia('(prefers-reduced-motion: reduce)');
let store,itemStates={},customItems=[],actor=localStorage.getItem('mundinho.actor')||'gr1d',currentRoute='inicio',openGuide=localStorage.getItem('mundinho.openGuide')||'twilight-forest',soundEnabled=false,phaseFilter=localStorage.getItem('mundinho.phaseFilter')||'Todos',refreshTimer;
actorSelect.value=actor;

function loader(){const grid=$('.chunk-grid');for(let i=0;i<20;i++){const b=document.createElement('span');b.style.animationDelay=`${i*28}ms`;grid.appendChild(b);}}
function beep(){if(!soundEnabled)return;try{const C=window.AudioContext||window.webkitAudioContext,a=new C(),o=a.createOscillator(),g=a.createGain();o.type='square';o.frequency.value=420;g.gain.setValueAtTime(.035,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+.07);o.connect(g);g.connect(a.destination);o.start();o.stop(a.currentTime+.07);}catch{}}
function toast(title,copy=''){const el=document.createElement('div');el.className='toast';el.innerHTML=`<strong>Advancement Made!</strong><b>${esc(title)}</b>${copy?`<small>${esc(copy)}</small>`:''}`;toastRegion.appendChild(el);setTimeout(()=>el.remove(),3800);}
function stateFor(id){return itemStates[id]||{};}
function defaults(){return allDefaultChecklistItems();}
function activeCustom(section,entryKey){return customItems.filter(x=>!x.deleted_at&&x.section===section&&(!entryKey||x.entry_key===entryKey));}
function allItems(){const d=defaults();const c=customItems.filter(x=>!x.deleted_at).map(x=>({id:`custom:${x.id}`,rawId:x.id,title:x.title,description:x.description||'',phase:x.phase||'',section:x.section,entryKey:x.entry_key,guideId:x.entry_key,guideTitle:guides.find(g=>g.id===x.entry_key)?.title||x.entry_key,custom:true,dbId:x.id}));return [...d,...c];}
function progressStats(){const items=allItems().filter(x=>x.section==='mods');const done=items.filter(x=>stateFor(x.id).completed).length;return{done,total:items.length,pct:items.length?Math.round(done/items.length*100):0};}
function nextUnchecked(){return allItems().find(x=>x.section==='mods'&&!stateFor(x.id).completed);}
function lastMarked(){return Object.entries(itemStates).filter(([,s])=>s.completed&&s.completed_at).sort((a,b)=>new Date(b[1].completed_at)-new Date(a[1].completed_at))[0];}
function skin(name,small=false){return `<span class="skin-face ${name} ${small?'small':''}" aria-label="skin de ${name}"></span>`;}
function pageHeader(title,subtitle=''){return `<div class="page-header"><div><h1 class="page-title">${esc(title)}</h1>${subtitle?`<p class="page-subtitle">${subtitle}</p>`:''}</div><div class="skin-row">${skin('gr1d')}${skin('benamu')}</div></div>`;}

function home(){const st=progressStats(),last=lastMarked(),next=nextUnchecked();let lastHtml='<p>Nada marcado ainda.</p>';if(last){const item=allItems().find(x=>x.id===last[0]);lastHtml=`<div class="last-marked">${skin(last[1].completed_by||'gr1d',true)}<div><strong>${esc(item?.title||last[0])}</strong><p>${esc(last[1].completed_by||'alguém')} · ${fmt(last[1].completed_at)}</p></div></div>`;}
const trophies=[['ignis-kill','Ignis'],['twilight-naga','Naga'],['twilight-lich','Lich'],['twilight-hydra','Hydra'],['twilight-urghast','Ur-Ghast'],['twilight-snowqueen','Snow Queen'],['twilight-keeper','Castle Keeper']].map(([raw,name])=>{const id=defaults().find(x=>x.rawId===raw)?.id;return `<div class="trophy ${id&&stateFor(id).completed?'':'locked'}">${esc(name)}</div>`}).join('');
return `<section class="page">${pageHeader('Mundinho · pra sempre','Wiki e diário do nosso foreverworld. Sem pressa; esse mundo é para durar.')}
<div class="hero-grid"><div class="hero-card"><span class="pixel-label">gr1d + benamu</span><h2>o nosso mundo</h2><p>Java 1.21.1 · NeoForge. A wiki cresce junto com o save, e as marcações ficam compartilhadas entre os dois.</p><div class="stat-grid"><div class="stat"><strong>${st.pct}%</strong><span>dos objetivos já cadastrados</span></div><div class="stat"><strong>${st.done}</strong><span>marcados</span></div><div class="stat"><strong>${st.total}</strong><span>objetivos atuais</span></div></div><div class="xp-wrap"><div class="xp-label"><span>progresso geral</span><span>${st.done}/${st.total}</span></div><div class="xp-bar"><div class="xp-fill" style="width:${st.pct}%"></div></div></div></div>
<figure class="hero-photo"><div style="aspect-ratio:16/9;display:grid;place-items:center;background:#2b2622;color:#ddceb4;padding:28px;text-align:center"><strong>foto do mundo</strong><br><small>espaço reservado para uma screenshot escolhida por nós</small></div><figcaption>uma foto daqui quando a gente escolher a definitiva</figcaption></figure></div>
<div class="home-stack" style="margin-top:22px"><div class="panel"><h2>último item marcado</h2>${lastHtml}</div><div class="panel next-step"><h2>próximo passo sugerido</h2>${next?`<strong>${esc(next.title)}</strong><p>${esc(next.guideTitle||next.entryKey||'objetivo do mundo')}</p>`:'<p>Os objetivos atuais estão todos marcados.</p>'}</div><div class="panel"><h2>estante de troféus</h2><div class="trophy-shelf">${trophies}</div></div></div></section>`;}

function checklistHtml(section,entryKey,baseItems,title='Checklist'){const custom=activeCustom(section,entryKey).map(x=>({id:`custom:${x.id}`,title:x.title,description:x.description||'',phase:x.phase||'',custom:true,dbId:x.id,entryKey}));const items=[...baseItems,...custom];return `<div class="checklist-shell"><div class="checklist-head"><h3>${esc(title)}</h3><button class="add-item" data-add-section="${section}" data-add-key="${esc(entryKey)}">+ adicionar item</button></div><div class="checklist">${items.length?items.map(checkItem).join(''):'<p>Nenhum item ainda.</p>'}</div></div>`;}
function checkItem(item){const s=stateFor(item.id),done=!!s.completed;return `<div class="check-item ${done?'done':''} ${item.custom?'custom':''}" data-item-id="${esc(item.id)}"><button class="check-box" role="checkbox" aria-checked="${done}" data-check="${esc(item.id)}" data-entry="${esc(item.entryKey||'')}">${done?'✓':''}</button><div><div class="check-title">${esc(item.title)}</div>${item.description?`<div class="check-desc">${esc(item.description)}</div>`:''}${item.phase?`<div class="check-meta">${esc(item.phase)}</div>`:''}${done?`<div class="check-meta">marcado por ${esc(s.completed_by||'?')} · ${fmt(s.completed_at)}</div>`:''}</div>${item.custom?`<button class="delete-item" data-delete="${esc(item.dbId)}" aria-label="Excluir ${esc(item.title)}">apagar</button>`:''}</div>`;}
function craft(c){const grid=c.grid?`<div class="crafting-grid">${c.grid.map(x=>`<div class="craft-slot ${x?'':'empty'}">${esc(x||'')}</div>`).join('')}</div>`:'';const ingredients=c.ingredients?`<ul>${c.ingredients.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:'';return `<div class="crafting-card"><div class="crafting-head"><h4>${esc(c.title)}</h4><span class="tag conf-${slug(c.confidence)}">confiança ${esc(c.confidence)}</span></div>${grid}${ingredients}${c.result?`<p class="craft-result">Resultado: ${esc(c.result)}</p>`:''}${c.body?`<p>${esc(c.body)}</p>`:''}</div>`;}
function guideCard(g){const base=g.checklist.map(([raw,title,phase])=>({id:`mods:${g.id}:${raw}`,rawId:raw,title,phase,section:'mods',entryKey:g.id,custom:false}));const open=openGuide===g.id;return `<article class="accordion ${open?'open':''}" id="guide-${g.id}" style="--guide-color:${g.color}"><button class="accordion-head" data-accordion="${g.id}" aria-expanded="${open}">${skin(g.id==='twilight-forest'?'benamu':'gr1d',true)}<span><h2>${esc(g.title)}</h2><small>${esc(g.subtitle)}</small></span><span class="accordion-icon">›</span></button><div class="accordion-panel-wrap"><div class="accordion-panel"><div class="guide-inner"><div class="guide-meta"><span class="tag">${esc(g.type)}</span><span class="tag diff-${slug(g.difficulty)}">${esc(g.difficulty)}</span><span class="tag risk-${slug(g.risk)}">risco ${esc(g.risk)}</span><span class="tag">${esc(g.phase)}</span><span class="tag conf-${slug(g.confidence)}">confiança ${esc(g.confidence)}</span></div><p>${esc(g.intro)}</p>${g.sections.map(([t,h])=>`<section class="guide-section"><h3>${esc(t)}</h3>${h}</section>`).join('')}<section class="guide-section"><h3>Craftings e usos dos materiais</h3>${g.craftings.map(craft).join('')}</section>${checklistHtml('mods',g.id,base,'Checklist formal')}<section class="guide-section"><h3>Links usados na calibração</h3><ul class="source-list">${g.sources.map(([n,u])=>`<li><a href="${u}" target="_blank" rel="noreferrer">${esc(n)}</a></li>`).join('')}</ul></section></div></div></div></article>`;}
function mods(){return `<section class="page">${pageHeader('Mods','A wiki central. Os guias entram sem inventar gates, receitas ou chefes.')}
<div class="accordion-list">${guides.map(guideCard).join('')}</div></section>`;}
function progression(){const items=defaults();const phases=['Início','Intermediário','Avançado','Pós-jogo'];return `<section class="page">${pageHeader('Progressão','Os marcos dos guias aparecem aqui. Sem dependência real, a ordem continua paralela em vez de virar uma fila inventada.')}<div class="toolbar">${['Todos',...phases].map(p=>`<button class="filter-chip ${phaseFilter===p?'active':''}" data-phase="${p}">${p}</button>`).join('')}<button class="add-item" data-add-section="progression" data-add-key="geral">+ adicionar item</button></div><div class="progress-columns">${phases.filter(p=>phaseFilter==='Todos'||phaseFilter===p).map(p=>`<div class="phase-column"><h2>${p}</h2><div class="phase-items">${items.filter(x=>x.phase===p).map(x=>`<div class="progress-card"><h3>${esc(x.title)}</h3><p>${esc(x.guideTitle)}</p></div>`).join('')||'<p>Sem marco deste lote.</p>'}${activeCustom('progression','geral').filter(x=>!x.phase||x.phase===p).map(x=>`<div class="progress-card"><h3>${esc(x.title)}</h3><p>${esc(x.description||'objetivo adicionado por nós')}</p></div>`).join('')}</div></div>`).join('')}</div></section>`;}
function extras(){return `<section class="page">${pageHeader('Extras','Objetivos de carinho não são progressão. A lista curada entra no Lote 4; o checklist próprio já está funcionando.')}${checklistHtml('extras','geral',[],'Objetivos nossos')}</section>`;}
function placeholder(route){const p=routePlaceholders[route];return `<section class="page">${pageHeader(p.title)}<div class="placeholder-card"><h2>esta página já tem lugar no mundo</h2><p>${esc(p.copy)}</p>${route==='bastidores'?`<p><strong>pack:</strong> ${siteMeta.version}</p><p><strong>sincronização:</strong> ${store?.mode==='supabase'?'Supabase compartilhado':'prévia local'}</p>`:''}</div></section>`;}
function render(){currentRoute=(location.hash||'#inicio').slice(1);if(!['inicio','progressao','mods','amendments','extras','bastidores'].includes(currentRoute))currentRoute='inicio';$$('.main-nav a').forEach(a=>a.classList.toggle('active',a.dataset.route===currentRoute));app.innerHTML=currentRoute==='inicio'?home():currentRoute==='progressao'?progression():currentRoute==='mods'?mods():currentRoute==='extras'?extras():placeholder(currentRoute);bindDynamic();app.focus({preventScroll:true});}
function bindDynamic(){$$('[data-accordion]').forEach(btn=>btn.onclick=()=>{const id=btn.dataset.accordion,box=btn.closest('.accordion'),will=!box.classList.contains('open');box.classList.toggle('open',will);btn.setAttribute('aria-expanded',will);if(will){openGuide=id;localStorage.setItem('mundinho.openGuide',id);beep();}});$$('[data-check]').forEach(btn=>btn.onclick=async()=>{const id=btn.dataset.check,was=!!stateFor(id).completed;try{await store.setCompleted(id,!was,actor,btn.dataset.entry);await refresh();if(!was){toast(allItems().find(x=>x.id===id)?.title||'Objetivo marcado',actor);beep();const fill=$('.xp-fill');if(fill&&!reduced.matches){fill.classList.add('bump');setTimeout(()=>fill.classList.remove('bump'),350);}}}catch(e){toast('Não deu para salvar',e.message);}});$$('[data-add-section]').forEach(btn=>btn.onclick=()=>openAdd(btn.dataset.addSection,btn.dataset.addKey));$$('[data-delete]').forEach(btn=>btn.onclick=()=>askDelete(btn.dataset.delete));$$('[data-phase]').forEach(btn=>btn.onclick=()=>{phaseFilter=btn.dataset.phase;localStorage.setItem('mundinho.phaseFilter',phaseFilter);render();});}
function openAdd(section,key){$('#item-scope-type').value=section;$('#item-scope-key').value=key;$('#item-title').value='';$('#item-description').value='';$('#item-difficulty').value='';$('#item-phase').value='';itemDialog.showModal();setTimeout(()=>$('#item-title').focus(),10);}
function askDelete(id){const row=customItems.find(x=>x.id===id);$('#confirm-copy').textContent=`“${row?.title||'este item'}” vai sumir da interface, mas o histórico fica no banco.`;confirmDialog.showModal();confirmDialog.addEventListener('close',async function once(){confirmDialog.removeEventListener('close',once);if(confirmDialog.returnValue==='confirm'){try{await store.deleteCustomItem(id,actor);await refresh();toast('Item guardado no histórico','soft delete');}catch(e){toast('Não deu para excluir',e.message);}}});}
async function refresh(){[itemStates,customItems]=await Promise.all([store.getStates(),store.getCustomItems()]);render();}
function scheduleRefresh(){clearTimeout(refreshTimer);refreshTimer=setTimeout(()=>refresh().catch(console.error),150);}

$('#item-form').addEventListener('submit',async e=>{if(e.submitter?.value==='cancel')return; e.preventDefault();const title=$('#item-title').value.trim();if(!title)return;const section=$('#item-scope-type').value,key=$('#item-scope-key').value;try{await store.addCustomItem({section,entry_key:key,title,description:$('#item-description').value.trim(),difficulty:$('#item-difficulty').value||null,phase:$('#item-phase').value||null},actor);itemDialog.close();await refresh();toast(title,'item colado no diário');}catch(err){toast('Não deu para adicionar',err.message);}});
actorSelect.onchange=()=>{actor=actorSelect.value;localStorage.setItem('mundinho.actor',actor);toast(`Agora é ${actor}`,'as próximas marcações usam este nome');};
$('#sound-toggle').onclick=e=>{soundEnabled=!soundEnabled;e.currentTarget.setAttribute('aria-pressed',soundEnabled);if(soundEnabled)beep();};
$('#search-open').onclick=()=>{searchDialog.showModal();searchInput.value='';doSearch('');setTimeout(()=>searchInput.focus(),20);};
searchInput.oninput=()=>doSearch(searchInput.value);
document.addEventListener('keydown',e=>{if(e.key==='/'&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName)){e.preventDefault();$('#search-open').click();}});
function doSearch(q){const term=q.trim().toLowerCase();const pool=[];guides.forEach(g=>pool.push({type:'Guia',title:g.title,copy:g.intro,route:'#mods',guide:g.id}));allItems().forEach(i=>pool.push({type:i.section==='extras'?'Extra':'Objetivo',title:i.title,copy:i.guideTitle||i.description||'',route:i.section==='extras'?'#extras':i.section==='progression'?'#progressao':'#mods',guide:i.guideId}));const result=pool.filter(x=>!term||`${x.title} ${x.copy}`.toLowerCase().includes(term)).slice(0,40);searchResults.innerHTML=result.map((x,i)=>`<button type="button" class="search-result" data-search-index="${i}"><strong>${esc(x.title)}</strong><small>${esc(x.type)} · ${esc(x.copy.slice(0,120))}</small></button>`).join('')||'<p>Nada por aqui.</p>';$$('[data-search-index]',searchResults).forEach(btn=>btn.onclick=()=>{const x=result[Number(btn.dataset.searchIndex)];if(x.guide){openGuide=x.guide;localStorage.setItem('mundinho.openGuide',openGuide);}searchDialog.close();location.hash=x.route;render();if(x.guide)setTimeout(()=>document.querySelector(`#guide-${x.guide}`)?.scrollIntoView({behavior:reduced.matches?'auto':'smooth',block:'start'}),80);});}
$('#export-json').onclick=async()=>{try{const payload=await store.exportAll();const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`mundinho-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href);toast('Backup exportado');}catch(e){toast('Falha no export',e.message);}};
$('#import-json').onchange=async e=>{const file=e.target.files?.[0];if(!file)return;try{const payload=JSON.parse(await file.text());await store.importAll(payload,actor);await refresh();toast('Backup importado','confira as marcações compartilhadas');}catch(err){toast('JSON não importado',err.message);}finally{e.target.value='';}};
window.addEventListener('hashchange',render);

async function init(){loader();store=await createStore();syncStatus.textContent=store.mode==='supabase'?'sincronização: Supabase compartilhado':'sincronização: prévia local';if(store.mode!=='supabase'){dbBanner.hidden=false;dbBanner.innerHTML='<strong>Prévia local.</strong> /api/config não entregou as variáveis do Supabase; as marcações ficam apenas neste navegador.';}try{await refresh();store.subscribe(scheduleRefresh);}catch(error){console.error(error);dbBanner.hidden=false;dbBanner.innerHTML=`<strong>Banco indisponível.</strong> ${esc(error.message)}`;}if(hasLegacyData()){migrationDialog.showModal();migrationDialog.addEventListener('close',async function once(){migrationDialog.removeEventListener('close',once);if(migrationDialog.returnValue==='migrate'){const r=await store.migrateLegacy(actor);await refresh();toast('Migração concluída',`${r.migrated||0} registros reconhecidos`);}else localStorage.setItem('mundinho.legacyMigrationDone','1');});}setTimeout(()=>{$('#chunk-loader').hidden=true;$('#site-shell').hidden=false;render();},reduced.matches?50:520);}
init();
