export const siteMeta={title:'Mundinho · pra sempre',subtitle:'wiki e diário de gr1d + benamu',version:'Java 1.21.1 · NeoForge',lote:'Lote 1 — Fundação'};

export const guides=[
{
id:'ignis',title:'Ignis',subtitle:"L_Ender's Cataclysm · chefe",type:'chefe',color:'#a5443d',difficulty:'Muito difícil',risk:'Severo',phase:'Pós-jogo',equivalent:'pós-Dragão / endgame',complexity:'Complexa',confidence:'Alta',
intro:'Ignis fecha a linha da Burning Arena. A luta só começa depois dos Ignited Revenants, das Burning Ashes e do Altar of Fire. São três fases, pressão de fogo/soul fire e uma arena que pode virar parte do problema.',
sections:[
['Onde encontrar / como começar',`<p><strong>Obrigatório:</strong> encontrar a <strong>Burning Arena</strong>, derrotar os <strong>Ignited Revenants</strong>, obter <strong>Burning Ashes</strong> e usar as cinzas no <strong>Altar of Fire</strong>.</p><div class="soft-block"><strong>Recomendação, não gate:</strong> Netherite muito bem encantada ou equivalente modded, arma forte, ranged, cura e backup de equipamento fora da arena.</div>`],
['Antes de sair',`<ul><li>Set principal completamente reparado.</li><li>Boa arma corpo a corpo e opção de ataque à distância.</li><li>Comida de alta saturação e cura.</li><li>Proteção contra fogo.</li><li>Blocos e uma forma de escapar de lava/quedas.</li><li>Backup de equipamento fora da arena.</li><li>Espaço no inventário para o loot.</li></ul>`],
['Progressão dentro da Burning Arena',`<h4>1. Limpar a arena</h4><p>Os Ignited Revenants fazem parte da preparação. O objetivo é conseguir as cinzas e entender a arena antes de invocar Ignis.</p><p><strong>Risco:</strong> Alto · <strong>Reversibilidade:</strong> Alta antes da invocação.</p><h4>2. Altar of Fire</h4><p>Não use as Burning Ashes só porque chegou ali. Este é o ponto em que exploração vira luta de boss.</p><h4>3. Fase 1</h4><p>Ignis mistura melee, ondas de fogo, terremoto, projéteis, tornados, slam e lifesteal. Primeiro objetivo: ler o ritmo.</p><h4>4. Fase 2</h4><p>Por volta de 67% de vida, entra a fase de soul fire e a pressão aumenta.</p><h4>5. Fase 3</h4><p>Por volta de 33%, a transição inclui explosão de soul fire. Aqui o chão importa quase tanto quanto a barra do boss.</p><h4>6. Ignitium</h4><p><strong>Ignitium Ingot</strong> é drop garantido. A quantidade exata fica para conferir in-game na versão 3.33 porque as fontes usadas na calibração divergiam.</p>`],
['Para não perder o inventário',`<div class="warning-block">O piso pode virar parte do perigo. Não lute colado em buracos, não carregue itens insubstituíveis sem função na luta e deixe um kit de recuperação fora da arena.</div>`]
],
craftings:[
{title:'Burning Ashes',confidence:'Alta',body:'Sem receita afirmada. As cinzas dos Ignited Revenants são usadas no Altar of Fire para invocar Ignis. Confiança alta para obtenção/uso; receita não inventada.'},
{title:'Ignitium Upgrade Smithing Template',confidence:'Alta',result:'1 × Ignitium Upgrade Smithing Template',grid:['Nether Bricks','Blaze Powder','Nether Bricks','Blaze Powder','Netherite Upgrade Smithing Template','Blaze Powder','Nether Bricks','Blaze Powder','Nether Bricks'],body:'Aplicado a equipamento Netherite usando Ignitium Ingot.'},
{title:'Block of Ignitium',confidence:'Alta',result:'1 × Block of Ignitium',grid:Array(9).fill('Ignitium Ingot'),body:'O processo inverso devolve 9 Ignitium Ingots.'},
{title:'The Incinerator',confidence:'Alta',ingredients:['4 × Blaze Rod','2 × Ignitium Ingot','1 × Netherite Sword'],body:'Ingredientes confirmados; grade não reproduzida sem confirmação equivalente.'},
{title:'Bulwark of the Flame',confidence:'Alta',ingredients:['4 × Nether Brick','2 × Ignitium Ingot','2 × Blaze Rod','1 × Shield'],body:'Ingredientes confirmados; grade omitida de propósito.'},
{title:'Blazing Grips',confidence:'Alta',ingredients:['8 × Nether Brick','1 × Ignitium Ingot'],body:'Ingredientes confirmados; grade omitida de propósito.'}
],
checklist:[['ignis-find-arena','Encontrar a Burning Arena','Avançado'],['ignis-revenants','Derrotar os dois Ignited Revenants','Avançado'],['ignis-ashes','Conseguir Burning Ashes','Avançado'],['ignis-gear','Preparar equipamento de endgame','Pós-jogo'],['ignis-altar','Localizar o Altar of Fire','Pós-jogo'],['ignis-summon','Invocar Ignis','Pós-jogo'],['ignis-phase1','Sobreviver à fase 1','Pós-jogo'],['ignis-phase2','Alcançar a fase 2','Pós-jogo'],['ignis-phase3','Alcançar a fase 3','Pós-jogo'],['ignis-kill','Derrotar Ignis','Pós-jogo'],['ignis-loot','Recolher Ignitium','Pós-jogo'],['ignis-craft','Produzir pelo menos um item de Ignitium','Pós-jogo']],
sources:[['Cataclysm no CurseForge','https://www.curseforge.com/minecraft/mc-mods/lendercataclysm'],['Wiki do Ignis','https://lendercataclysm.wiki.gg/wiki/Ignis'],['Dados de recipes / Ignitium','https://blockmicroscope.com/mods/cataclysm/ignitium-ingot']]
},
{
id:'twilight-forest',title:'The Twilight Forest',subtitle:'dimensão + família de add-ons do pack',type:'dimensão',color:'#557a46',difficulty:'Exige preparo → Difícil no fim',risk:'Médio',phase:'Início → Pós-jogo',equivalent:'pré-Nether → pós-Dragão',complexity:'Moderada',confidence:'Alta',
intro:'Uma dimensão inteira com biomas, estruturas, loot, dungeons e progressão ambiental. No pack ela vem com Spiced Twilight, Dungeons & Villages, Twilight Treehouses e Twilight Forest Final Boss.',
sections:[
['Como entrar',`<p>O portal usa uma piscina de pelo menos <strong>2×2 de água</strong>, borda de blocos de terra compatíveis, vegetação sobre a borda e <strong>1 Diamond</strong> jogado na água como ativador.</p><p><strong>Obrigatório:</strong> portal válido + Diamond. <strong>Soft:</strong> ferro completo, shield, comida e arma razoável.</p><div class="note-block">Entrar na dimensão não significa estar pronto para terminar a dimensão.</div>`],
['Antes de sair',`<ul><li>Diamond para ativar o portal.</li><li>Comida, shield, arma corpo a corpo e arco.</li><li>Tochas, blocos e espaço para loot.</li><li>Materiais para marcar o portal.</li><li>Assim que possível, montar uma Magic Map.</li></ul>`],
['Progressão — ordem que realmente importa',`<h4>1. Naga</h4><p>Primeiro boss. Vencê-la libera a linha da Lich Tower. Risco médio, mecânica simples, fase Início.</p><h4>2. Twilight Lich</h4><p>Depois da Naga. A derrota do Lich libera três grandes linhas posteriores. Risco alto, mecânica moderada, fase Intermediário.</p><h4>3. Três trilhas paralelas</h4><p><strong>Pântano:</strong> Labyrinth → Minoshroom → Meef Stroganoff → Fire Swamp → Hydra.</p><p><strong>Dark Forest:</strong> Goblin Stronghold / Knight Phantoms → Dark Tower → Ur-Ghast.</p><p><strong>Gelada:</strong> Alpha Yeti → Aurora Palace → Snow Queen.</p><div class="soft-block"><strong>Entre as três:</strong> trilha paralela — ordem indiferente.</div><h4>4. Highlands</h4><p>Hydra + Ur-Ghast + Snow Queen liberam a região. Depois entram Trolls, Magic Beans, Giants e Lamp of Cinders.</p><h4>5. Final Castle + Castle Keeper</h4><p>Nosso pack inclui Twilight Forest Final Boss 2.1.2. Existência/posição do Castle Keeper: confirmada. Gatilho exato da versão instalada: <strong>Baixa-conferir</strong>.</p>`],
['Conteúdo paralelo',`<p>Treehouses e estruturas/villages dos add-ons entram como objetivos opcionais. Spiced Twilight se distribui pelas etapas correspondentes; não vira gate artificial.</p>`],
['Para não perder o inventário',`<div class="warning-block">Se uma região começar a punir vocês ambientalmente, primeiro confiram a progressão. Twilight Forest usa gates ambientais; não assumam que é só um biome difícil que dá para tankar.</div>`]
],
craftings:[
{title:'Portal para Twilight Forest',confidence:'Alta',ingredients:['mínimo funcional: 4 blocos de água','borda de terra compatível','plantas sobre a borda','1 × Diamond como ativador'],body:'Não é crafting de bancada.'},
{title:'Magic Map Focus',confidence:'Alta',ingredients:['1 × Raven Feather','1 × Torchberries','1 × Glowstone Dust'],result:'Magic Map Focus',body:'Receita shapeless.'},
{title:'Blank Magic Map',confidence:'Alta',grid:['Paper','Paper','Paper','Paper','Magic Map Focus','Paper','Paper','Paper','Paper'],result:'Blank Magic Map'},
{title:'Maze Map',confidence:'Alta',grid:['Paper','Paper','Paper','Paper','Maze Map Focus','Paper','Paper','Paper','Paper'],result:'Maze Map',body:'Maze Map Focus não recebe receita inventada; é conteúdo obtido no Labyrinth.'},
{title:'Ore Map',confidence:'Alta',ingredients:['1 × Maze Map','1 × Diamond Block','1 × Gold Block','1 × Iron Block'],result:'Ore Map',body:'Receita shapeless.'},
{title:'Raw Ironwood → Ironwood Ingot',confidence:'Alta',ingredients:['Liveroot','Raw Iron','Gold Nugget'],result:'2 × Raw Ironwood',body:'Shapeless; depois Raw Ironwood → smelting ou blasting → Ironwood Ingot.'}
],
checklist:[['twilight-portal','Construir e ativar o portal','Início'],['twilight-enter','Entrar na Twilight Forest','Início'],['twilight-map','Fazer a Magic Map','Início'],['twilight-naga-find','Encontrar a Naga Courtyard','Início'],['twilight-naga','Derrotar Naga','Início'],['twilight-lich-find','Encontrar a Lich Tower','Intermediário'],['twilight-lich','Derrotar Twilight Lich','Intermediário'],['twilight-minoshroom','Encontrar e derrotar Minoshroom','Intermediário'],['twilight-stroganoff','Completar a etapa do Meef Stroganoff','Intermediário'],['twilight-hydra','Derrotar Hydra','Avançado'],['twilight-knights','Derrotar Knight Phantoms','Intermediário'],['twilight-urghast','Derrotar Ur-Ghast','Avançado'],['twilight-yeti','Derrotar Alpha Yeti','Intermediário'],['twilight-snowqueen','Derrotar Snow Queen','Avançado'],['twilight-highlands','Liberar Highlands','Avançado'],['twilight-trolls','Explorar Troll Caves','Avançado'],['twilight-beans','Obter Magic Beans','Avançado'],['twilight-giants','Completar a etapa dos Giants','Avançado'],['twilight-lamp','Obter/usar Lamp of Cinders','Avançado'],['twilight-castle','Chegar ao Final Castle','Pós-jogo'],['twilight-keeper-find','Encontrar o Castle Keeper','Pós-jogo'],['twilight-keeper','Derrotar Castle Keeper','Pós-jogo'],['twilight-treehouse','Encontrar pelo menos uma Twilight Treehouse','Intermediário'],['twilight-dnv','Encontrar conteúdo de Dungeons & Villages','Intermediário'],['twilight-museum','Guardar um troféu de cada boss importante para o museu','Pós-jogo']],
sources:[['Twilight Forest no CurseForge','https://www.curseforge.com/minecraft/mc-mods/the-twilight-forest'],['Twilight Forest Final Boss','https://www.curseforge.com/minecraft/mc-mods/twilight-forest-final-boss'],['Twilight Treehouses','https://modrinth.com/mod/twilight-treehouses/version/1.0.2'],['Dungeons & Villages','https://modrinth.com/mod/the-twilight-forest-dungeons-villages/version/2.0.3']]
},
{
id:'sophisticated-backpacks',title:'Sophisticated Backpacks',subtitle:'utilidade · armazenamento',type:'utilidade',color:'#8b633d',difficulty:'Tranquilo',risk:'Baixo',phase:'Início → endgame',equivalent:'pré-Nether',complexity:'Simples → Moderada',confidence:'Alta',
intro:'Mochilas carregáveis ou colocáveis no mundo, tiers de capacidade e upgrades para coleta, crafting, filtros, stack size, alimentação, processamento e automação. Cresce junto com o mundo; não é uma campanha com fim obrigatório.',
sections:[
['Como começar',`<p><strong>Obrigatório:</strong> só os materiais da primeira Backpack. Não existe requisito de armadura, dimensão, boss ou avanço vanilla.</p><div class="note-block">A mochila entra cedo. Esperar Netherite para começar seria como esperar Elytra para fazer um baú.</div>`],
['Progressão recomendada',`<h4>1. Primeira Backpack</h4><p>Faça uma quando o custo não estiver competindo com necessidades básicas.</p><h4>2. Definir função</h4><p>Exploração, construção, comida ou loot de dungeon. Especialização evita a mochila virar um buraco negro de item.</p><h4>3. Subir tiers</h4><p>Leather → Copper → Iron → Gold → Diamond → Netherite. Suba por espaço e slots, não por obrigação.</p><h4>4. Upgrade Base</h4><p>Abre a parte modular.</p><h4>5. Resolver problemas reais</h4><p>Sequência sugerida: <strong>Pickup → Stack → Crafting</strong>. Depois Feeding, Magnet, Refill, Deposit, Smelting/Blasting conforme necessidade.</p><h4>6. Automação avançada</h4><p>Mochilas colocadas no mundo podem entrar em fluxos complexos. Inception permite backpacks dentro de backpack, limitado a um nível.</p>`],
['Antes de sair',`<ul><li>Backpack equipada e com espaço livre.</li><li>Filtros revisados.</li><li>Itens essenciais não ficaram numa mochila deixada na base.</li><li>Se usar Pickup/Magnet, conferir para onde o loot vai.</li><li>Se usar Void Upgrade, conferir o filtro duas vezes.</li></ul>`],
['Para não perder o inventário',`<div class="warning-block">O perigo aqui é configuração. Um filtro errado no Void Upgrade pode destruir loot. Antes de atualizar/remover o mod, faça backup do mundo.</div>`]
],
craftings:[
{title:'Backpack base',confidence:'Média',ingredients:['Leather','String','Chest'],body:'Ingredientes conhecidos. A disposição exata não é afirmada sem confirmação equivalente: conferir a disposição no JEI.'},
{title:'Upgrade Base',confidence:'Alta',result:'Upgrade Base',grid:['String','Iron Ingot','String','Iron Ingot','Leather','Iron Ingot','String','Iron Ingot','String']},
{title:'Crafting Upgrade',confidence:'Alta',result:'Crafting Upgrade',grid:['','Crafting Table','','Iron Ingot','Upgrade Base','Iron Ingot','','Chest',''],body:'Adiciona uma grade de crafting dentro da interface da mochila.'},
{title:'Pickup Upgrade',confidence:'Alta',ingredients:['1 × Sticky Piston','2 × String','1 × Upgrade Base','3 × Redstone Dust'],body:'Ingredientes e função confirmados; grade omitida sem a mesma segurança. Envia itens coletados direto para a mochila e aceita filtros.'},
{title:'Blasting Upgrade',confidence:'Alta',result:'Blasting Upgrade',grid:['Redstone','Iron Ingot','Redstone','Iron Ingot','Upgrade Base','Iron Ingot','Redstone','Blast Furnace','Redstone'],body:'Há também rota alternativa a partir de Smelting Upgrade + Iron Ingots + Smooth Stone.'}
],
checklist:[['backpack-first','Criar a primeira Backpack','Início'],['backpack-key','Configurar a tecla de abrir mochila','Início'],['backpack-carry','Testar usar a mochila carregada','Início'],['backpack-place','Testar colocá-la no mundo','Início'],['backpack-base','Fazer Upgrade Base','Início'],['backpack-upgrade','Instalar o primeiro upgrade','Início'],['backpack-pickup','Fazer Pickup Upgrade','Intermediário'],['backpack-filter','Configurar filtros de Pickup','Intermediário'],['backpack-stack','Fazer pelo menos um Stack Upgrade','Intermediário'],['backpack-crafting','Fazer Crafting Upgrade','Intermediário'],['backpack-copper','Evoluir para Copper','Início'],['backpack-iron','Evoluir para Iron','Intermediário'],['backpack-gold','Evoluir para Gold','Intermediário'],['backpack-diamond','Evoluir para Diamond','Avançado'],['backpack-netherite','Evoluir para Netherite','Pós-jogo'],['backpack-explore','Montar uma mochila especializada para exploração','Intermediário'],['backpack-second','Montar uma segunda mochila com função diferente','Intermediário'],['backpack-auto','Experimentar pelo menos um upgrade de automação','Avançado']],
sources:[['Sophisticated Backpacks no Modrinth','https://modrinth.com/mod/sophisticated-backpacks'],['Arquivo 3.26.3.2158','https://www.curseforge.com/minecraft/mc-mods/sophisticated-backpacks/files/8845926'],['Dados de Crafting Upgrade','https://blockmicroscope.com/mods/sophisticatedbackpacks/crafting-upgrade']]
}
];

export const routePlaceholders={
amendments:{title:'Amendments',copy:'A página fixa já existe na navegação. O catálogo por tema de Amendments + família Supplementaries entra no Lote 4, sem texto genérico improvisado.'},
extras:{title:'Extras',copy:'A estrutura e o checklist compartilhado já funcionam aqui. As 15–20 ideias de carinho específicas do pack entram no Lote 4; vocês já podem adicionar objetivos próprios.'},
bastidores:{title:'Bastidores',copy:'A página técnica existe e mostra o estado do pack/banco. A lista curta de libs, performance, tradução, correções e cosméticos entra no Lote 4 a partir da fonte de verdade aprovada.'}
};

export function allDefaultChecklistItems(){return guides.flatMap(g=>g.checklist.map(([rawId,title,phase])=>({id:`mods:${g.id}:${rawId}`,rawId,title,phase,section:'mods',entryKey:g.id,guideId:g.id,guideTitle:g.title,custom:false})));}
