export const amendmentsSections=[
{title:'Caldeirões',items:['Podem armazenar líquidos e têm interações próprias com líquidos.','Permitem mistura de poções e dyes; o mod possui receitas próprias de cauldron crafting.','Água/poções podem ferver sobre fonte de calor; caldeirão fervendo pode causar dano.','Entrar em splash/lingering potion no caldeirão aplica o efeito correspondente.']},
{title:'Escrita, placas e exposição',items:['Lecterns com Book and Quill ganham interface para escolher cor de tinta e fonte; também podem interagir com hoppers.','Hanging Signs podem segurar itens nas duas faces; com Supplementaries, podem exibir padrões de banner.','Signs têm modelo, textura e hitbox ajustados para consistência de pixel.']},
{title:'Luzes e física',items:['Lanterns ganham animação 3D na mão e podem ser penduradas em paredes.','Lanternas penduradas e hanging signs podem balançar com física.']},
{title:'Decoração que vira interação',items:['Mob skulls podem ser empilhadas e receber candles, com overlay de cera.','Banners e pots podem ser colocados no teto.','Tripwire Hooks podem segurar ferramentas com shift-click.','Carpeted stairs, double cakes e better lilypads fazem parte do conjunto de pequenas melhorias do mod.']},
{title:'Projéteis e cargas',items:['Dragon Charges passam a ser craftáveis.','Fire Charges ganham modelos, partículas e gravity melhorados e podem incendiar entidades em área.','Snowballs e slimeballs têm modelos 3D; snowballs aplicam freezing no impacto.','Snowballs e fireballs interagem com fogo e água.']},
{title:'Interface',items:['A versão 2.1.10 para 1.21.1 inclui nova UI de trades de villagers.']}
];

export const amendmentsSources=[
['Amendments — página do projeto','https://www.curseforge.com/minecraft/mc-mods/amendments'],
['Amendments — features','https://modrinth.com/mod/amendments'],
['Arquivo 2.1.10 NeoForge','https://www.curseforge.com/minecraft/mc-mods/amendments/files/8825641']
];

export const backstageGroups=[
{title:'Performance & renderização',mods:[
['EntityCulling','Evita renderizar entidades ocultas e reduz custo gráfico.'],['Ferrite Core','Reduz uso de memória; dois JARs seguem a conferir.'],['ImmediatelyFast','Otimiza caminhos de renderização; dois JARs seguem a conferir.'],['Iris','Suporte a shaders/renderização no cliente.'],['Krypton FNP','Otimiza a pilha de rede.'],['Lithium','Otimizações gerais de lógica/ticks.'],['ModernFix','Performance e correções; dois JARs seguem a conferir.'],['Sodium','Renderizador otimizado.'],['Sodium Extra','Opções extras de configuração/performance para Sodium.']]},
{title:'Bibliotecas, APIs & configuração',mods:[
['Architectury','Camada/biblioteca usada por outros mods.'],['BaguetteLib','Biblioteca de suporte.'],['Balm','Biblioteca compartilhada por mods do Blay.'],['Cerbons API','API usada por mods Cerbon.'],['Citadel','Biblioteca de entidades/animações usada por mods de Alex.'],['Cloth Config v15 API','Tela/API de configuração.'],['CodxLib','Biblioteca usada por Alex\'s Mobs Continued.'],['CoroUtil','Biblioteca/utilitários compartilhados.'],['CreativeCore','Biblioteca base de mods CreativeMD.'],['Cupboard mod','Biblioteca e integração de dados.'],['Curios API','API de slots de acessórios.'],['Delight Lib','Biblioteca de addons do Farmer\'s Delight.'],['Framework','Biblioteca usada por mods MrCrayfish.'],['GeckoLib 4','Biblioteca de animações de entidades/blocos.'],['GlitchCore','Biblioteca/base de worldgen e config.'],['GroovyModLoader','Loader/scripting para integrações e ajustes.'],['Iceberg','Biblioteca de utilitários.'],['Integrated API','API da família Integrated.'],['Kiwi Library','Biblioteca de suporte.'],['Library ferret','Biblioteca de suporte.'],['Lithostitched','Biblioteca/worldgen para datapacks e estruturas.'],['MezzConfig','Biblioteca/configuração.'],['Moonlight Lib','Biblioteca de MehVahdJukaar.'],['OctoLib','Biblioteca usada por mods Octo Studios.'],['Player Animation Library','Biblioteca de animação do jogador.'],['Puzzles Lib','Biblioteca de Fuzs.'],['Resourceful Lib','Biblioteca compartilhada.'],['Resourcefulconfig','Sistema de configuração.'],['Sophisticated Core','Base obrigatória do Sophisticated Backpacks.'],['TerraBlender','Biblioteca de worldgen/biomas.'],['YUNG\'s API','Base dos mods YUNG\'s.'],['YetAnotherConfigLib','Biblioteca de telas/configuração.'],['Zeta','Biblioteca/base do Quark.'],['gaboulibs','Biblioteca de suporte.'],['lionfishapi','API usada pelo Cataclysm.'],['oωo','Biblioteca/API.']]},
{title:'Visual, animação & áudio',mods:[
['3d-Skin-Layers','Camadas 3D para a skin do jogador.'],['Advancement Plaques','Muda a apresentação visual dos advancements.'],['AmbientSounds','Ambiência sonora por bioma/local.'],['Cave Dust Rethinking','Partículas de poeira/ambiente em cavernas.'],['Eating Animation','Animação visual ao comer/beber.'],['Emotecraft','Emotes sociais do jogador.'],['EMF Compat: Core','Base de compatibilidade do Entity Model Features.'],['EMF Compat: Not Enough Animations','Compatibilidade EMF com Not Enough Animations.'],['EMF Compat: Supplementaries','Compatibilidade visual EMF com Supplementaries.'],['EMF Compat: Take a Seat','Compatibilidade visual EMF com Take a Seat.'],['Entity Model Features','Modelos de entidade customizados.'],['Entity Texture Features','Texturas, emissivos e variações de entidades.'],['FirstPerson','Renderiza o corpo/modelo em primeira pessoa.'],['LambDynamicLights','Luz dinâmica segurando itens/fontes luminosas.'],['NotEnoughAnimations','Animações adicionais do jogador.'],['Particular Reforged','Partículas e pequenos efeitos visuais.'],['Presence Footsteps (NeoForge)','Passos contextuais por superfície.'],['Sound Physics Remastered','Reverberação, oclusão e acústica ambiental.'],['Visuality: Reforged','Partículas ambientais extras.'],['Wakes','Rastros/ondas na água.'],['What Are They Up To','Mostra ações/estado visual de outros jogadores.']]},
{title:'QoL, navegação & interface',mods:[
['AppleSkin','Mostra fome/saturação e informação de comida no HUD.'],['Corpse','Guarda inventário em corpo após morte.'],['Corpse Curios Compatibility','Preserva/integra slots Curios com Corpse.'],['Explorer\'s Compass','Localiza estruturas; Bastidores por decisão aprovada.'],['Just Enough Effects Descriptions','Descrição de efeitos/status no HUD.'],['Just Enough Items','Consulta de receitas e usos; último recurso quando documentação não fecha.'],['Nature\'s Compass','Localiza biomas; Bastidores por decisão aprovada.'],['Only TP','Restringe utilidade de comandos para teleport conforme configuração.'],['Xaero\'s Minimap','Minimapa/HUD.'],['Xaero\'s World Map','Mapa-múndi do save.']]},
{title:'Compatibilidade, correções & integrações',mods:[
['Cataclysm x YUNG\'s Better Nether Fortresses Compat','Integra Cataclysm com Better Nether Fortresses.'],['Incendium Translation Fix','Correções/tradução para Incendium.'],['Lootintegrations mod','Base de integração de loot entre mods e estruturas.'],['MoreRelics New Relics Fix','Corrige novas relics do More Relics.'],['Reliquified Twilight Forest new relics fix','Corrige relics novas do addon Twilight.'],['Waystones2Waypoints2','Sincroniza Waystones com waypoints/mapa.'],['Zeta Registry Race Fix','Correção de race condition/registro do Zeta.'],['fpm_x_compat','Compatibilidade de animação do FirstPerson.'],['lootintegrations_cataclysm mod','Integra loot do Cataclysm.'],['lootintegrations_dnt mod','Integra loot de Dungeons & Taverns.'],['lootintegrations_integrated mod','Integra loot da família Integrated.']]}
];

export const extraSuggestionPool=[
{title:'Fazer um quarto de hóspedes dimensional',description:'Construir um mini quarto temático para Aether, Twilight ou Undergarden dentro da base.'},
{title:'Noite de pesca e cozinha',description:'Passar uma noite pescando e usar o que vier numa refeição de Farmer\'s Delight.'},
{title:'Tour de trem sem objetivo útil',description:'Criar um trecho da Create só porque a vista é bonita.'},
{title:'Caixa de lembranças da primeira dimensão',description:'Guardar um item simples da primeira visita a cada dimensão, mesmo que não seja raro.'},
{title:'Observatório de mobs',description:'Montar um ponto seguro para observar criaturas novas sem transformar tudo em farm.'},
{title:'Livro de viagens do casal',description:'Usar Book and Quill para registrar uma frase ou lembrança de cada grande expedição.'},
{title:'Ponte bonita onde ninguém precisava',description:'Construir uma ponte só porque a paisagem pediu.'},
{title:'Reformar uma vila encontrada por acaso',description:'Escolher uma vila secundária e dar a ela um pequeno projeto de carinho.'},
{title:'Jardim de relíquias',description:'Expor relíquias favoritas junto de plantas e blocos que combinem com cada uma.'},
{title:'Acampamento permanente de exploração',description:'Transformar um acampamento temporário antigo em um posto pequeno e confortável.'},
{title:'Foto depois de uma luta horrível',description:'Quando um boss quase acabar com os dois, tirar uma screenshot da volta para casa.'},
{title:'Sala de mapas e portais',description:'Organizar mapas, Waystones e portais em uma sala que conte a geografia do mundo.'}
];
