export const lote3Part2 = [
  {
    "id":"supplementaries","title":"Família Amendments / Supplementaries","subtitle":"Supplementaries + Supplementaries Squared","type":"vanilla+ funcional","color":"#7c6b52","difficulty":"Tranquilo","risk":"Baixo","phase":"Início","equivalent":"pré-Nether","complexity":"Moderada","confidence":"Alta","intro":"Supplementaries preenche buracos do vanilla com objetos funcionais: jars, signposts, faucets, sconces, planters, redstone e decoração. Squared amplia esse vocabulário.",
    "sections":[["Como usar","Não tente 'zerar' o mod. Adote um bloco quando ele resolver algo: sinalização, armazenamento, iluminação, água, redstone ou detalhe de build."],["Integração com sede","Na integração 1.21.1, Jars, Goblets e Faucets preservam o grau de pureza da água; isso faz Supplementaries conversar diretamente com o sistema de sede."],["Amendments","Amendments tem página fixa própria no Lote 4. Aqui ficam Supplementaries e Supplementaries Squared; não misturar as duas responsabilidades."]],
    "craftings":[{"title":"Jars / Faucets / utilidades","confidence":"Média","body":"As receitas são por item e variam com tags/materiais. Não reproduzimos grade genérica. Para cada peça importante, recipe data > ingredientes confirmados > JEI como último recurso."}],
    "checklist":[["supp-jar","Usar um Jar para armazenamento ou água","Início"],["supp-sign","Criar sinalização funcional para a base","Início"],["supp-redstone","Usar um bloco funcional em redstone/automação","Intermediário"]],"sources":[["Supplementaries","https://modrinth.com/mod/supplementaries"]]
  },
  {
    "id":"friends-foes","title":"Friends&Foes","subtitle":"Copper Golem, Glare, Rascal, Iceologer, Wildfire e mais","type":"mobs / mecânicas","color":"#aa814e","difficulty":"Moderada","risk":"Médio","phase":"Início → Intermediário","equivalent":"pré-Nether → Nether-pré-Fortress","complexity":"Moderada","confidence":"Alta","intro":"Os mobs rejeitados de votações viram conteúdo vanilla+. Metade é companhia/utilidade; a outra metade é encontro hostil. Não trate todos como 'só skin'.",
    "sections":[["Conteúdo amigável","Copper Golem, Crab, Glare, Moobloom, Rascal e Tuff Golem têm interações próprias. Glare, por exemplo, usa glow berries para tame/breed e indica áreas escuras."],["Conteúdo hostil","Iceologer vive em cabanas de spruce em regiões frias. Wildfire e outros hostis entram como encontros paralelos; ferro completo + escudo/ranged é preparo confortável."],["Copper Golem","Há workstation/estrutura ligada ao Copper Golem e variantes de copper buttons/lightning rods. É um mini-sistema, não apenas mob decorativo."]],
    "craftings":[{"title":"Tame/Breed do Glare","confidence":"Alta","body":"Usa Glow Berries; é interação com item, não crafting."},{"title":"Receitas de copper variants","confidence":"Média","body":"Existem receitas para blocos/variantes associados ao Copper Golem. Como são várias e dependem de oxidação, o guia não inventa uma grade única."}],
    "checklist":[["foes-glare","Encontrar e interagir com um Glare","Início"],["foes-copper","Encontrar/criar conteúdo do Copper Golem","Início"],["foes-rascal","Encontrar um Rascal","Intermediário"],["foes-iceologer","Derrotar um Iceologer","Intermediário"],["foes-wildfire","Sobreviver a um encontro com Wildfire","Intermediário"]],"sources":[["Friends&Foes","https://www.curseforge.com/minecraft/mc-mods/friends-and-foes-forge"]]
  },
  {
    "id":"illager-invasion","title":"Illager Invasion","subtitle":"novos illagers, raids e estruturas","type":"mobs / invasão","color":"#6b5d58","difficulty":"Difícil","risk":"Alto","phase":"Intermediário","equivalent":"Nether-pré-Fortress","complexity":"Moderada","confidence":"Alta","intro":"Quase uma dúzia de illagers novos entram em raids e estruturas. O perigo é volume + ranged + efeitos; a preparação é mais importante que qualquer ordem.",
    "sections":[["Primeiro contato","Ferro completo, escudo, arco e leite deixam a curva justa. Alguns illagers aparecem em estruturas, outros reforçam raids."],["Raids","Raids deixam de ser o conjunto vanilla previsível. Limpe terreno, tenha cobertura e não dependa de uma única rota até os villagers."],["Loot","O mod oferece recompensas próprias, mas não existe uma campanha de crafting necessária para acessar o conteúdo."]],
    "craftings":[{"title":"Receitas","confidence":"Alta","body":"Não há item obrigatório de crafting para 'ativar' Illager Invasion. O conteúdo entra naturalmente por estruturas/raids."}],
    "checklist":[["illager-structure","Encontrar conteúdo estrutural do mod","Intermediário"],["illager-new","Derrotar pelo menos três tipos novos de illager","Intermediário"],["illager-raid","Concluir uma raid com Illager Invasion ativo","Intermediário"]],"sources":[["Illager Invasion","https://www.curseforge.com/minecraft/mc-mods/illager-invasion"]]
  },
  {
    "id":"structures","title":"Masmorras, estruturas & assentamentos","subtitle":"Dungeons & Taverns + WDA + YUNG's + Integrated Seven Seas + Better Village","type":"exploração","color":"#7d6650","difficulty":"Moderada → Difícil","risk":"Alto","phase":"Início → Avançado","equivalent":"pré-Nether → pré-Ender Dragon","complexity":"Moderada","confidence":"Alta","intro":"Este é o grande pacote de world structures. A regra é por escala, não por mod: estruturas pequenas cedo; dungeons reformuladas no meio; megaestruturas e conteúdo aquático quando o gear acompanhar.",
    "sections":[["Início","Vilas melhoradas, pontes, tavernas e estruturas pequenas. Ferro + escudo já basta para a maioria; use-as como loot e pontos de orientação."],["Intermediário","YUNG's Better Mineshafts/Dungeons/Temples/Witch Huts aumentam salas e armadilhas. Arco, balde d'água e blocos passam a valer muito."],["Grandes complexos","When Dungeons Arise merece staging: cama/waystone perto, inventário vazio e diamante parcial/completo. Retirada pode demorar."],["Água","YUNG's Better Ocean Monuments + Integrated Seven Seas pedem Water Breathing/Respiration e plano de recuperação."],["Nether/Stronghold","Better Nether Fortresses entra para blaze rods e exploração; Better Stronghold converge com End Remastered, mas não substitui a coleta dos 12 olhos."]],
    "craftings":[{"title":"Craftings","confidence":"Alta","body":"O grupo é majoritariamente worldgen. Não existe uma receita de entrada comum; chaves/loot específicos são documentados somente por estrutura quando houver fonte da versão."}],
    "checklist":[["struct-small","Explorar uma vila/taverna/ponte melhorada","Início"],["struct-yung","Limpar uma estrutura YUNG's reformulada","Intermediário"],["struct-wda","Concluir uma megaestrutura de When Dungeons Arise","Intermediário"],["struct-ocean","Concluir conteúdo marítimo reformulado","Avançado"],["struct-fortress","Explorar Better Nether Fortress","Intermediário"],["struct-stronghold","Explorar Better Stronghold","Avançado"]],"sources":[["When Dungeons Arise","https://modrinth.com/mod/when-dungeons-arise"]]
  },
  {
    "id":"mca","title":"Minecraft Comes Alive","subtitle":"MCA Reborn + Social Expansion + MCA: Quests","type":"social / vila","color":"#a96f62","difficulty":"Tranquilo","risk":"Baixo","phase":"Início → Intermediário","equivalent":"pré-Nether","complexity":"Moderada","confidence":"Alta","intro":"MCA transforma villagers em pessoas com relações, família e rotina. Os add-ons colocam quests em cima disso. É uma trilha social paralela ao combate.",
    "sections":[["Primeiro passo","Ache uma vila, proteja minimamente a área e converse com NPCs antes de tentar otimizar relações. NPC morto continua sendo um problema bem mais chato que um trade perdido."],["Relações e rotina","Conheça personalidade, presentes/interações e estrutura familiar do MCA. A progressão aqui é social, sem tier de armadura."],["MCA: Quests","Abra o menu Quests do villager, aceite trabalhos e volte para recompensa. O addon tem mais de 260 quests, chains, projetos de vila e recompensas incluindo itens, XP, reputação, títulos e relationship hearts."],["Social Expansion","Use como ampliação da vida da vila, não como gate para começar MCA."]],
    "craftings":[{"title":"Craftings","confidence":"Média","body":"MCA possui itens/objetos próprios, mas não há uma única receita central para iniciar relações. O guia prioriza interação/quests; receitas específicas ficam por item quando confirmadas."}],
    "checklist":[["mca-village","Estabelecer uma vila MCA segura","Início"],["mca-friend","Construir uma relação positiva com um NPC","Início"],["mca-quest","Completar a primeira quest de MCA: Quests","Intermediário"],["mca-chain","Completar uma pequena cadeia/projeto de vila","Intermediário"]],"sources":[["MCA Reborn","https://modrinth.com/mod/minecraft-comes-alive-reborn"],["MCA: Quests","https://www.curseforge.com/minecraft/mc-mods/mca-quests"]]
  }
];
