export const lote3Part3 = [
  {
    "id":"overworld-vivo","title":"Overworld vivo","subtitle":"Ecologics + Immersive Weathering","type":"ambientação jogável","color":"#71835d","difficulty":"Tranquilo","risk":"Baixo","phase":"Início","equivalent":"pré-Nether","complexity":"Simples","confidence":"Alta","intro":"O mundo muda e parece menos estático: novos detalhes ecológicos e weathering progressivo. É conteúdo para observar e usar, não uma campanha separada.",
    "sections":[["Ecologics","Procure biomas/fauna e recursos novos durante exploração normal. Não há gate global."],["Immersive Weathering","Moss, rust, erosion e transformações ambientais podem alterar builds/rotas ao longo do tempo. Considere isso quando o bloco tiver função estrutural ou visual importante."]],
    "craftings":[{"title":"Craftings","confidence":"Média","body":"Os dois mods possuem receitas pontuais, mas a função principal é world interaction/worldgen. Não há receita obrigatória de entrada."}],
    "checklist":[["living-ecologics","Encontrar conteúdo novo de Ecologics","Início"],["living-weather","Observar uma transformação do Immersive Weathering","Início"],["living-build","Usar uma mecânica ambiental de propósito numa build","Intermediário"]],"sources":[["Ecologics","https://modrinth.com/mod/ecologics"],["Immersive Weathering","https://modrinth.com/mod/immersive-weathering"]]
  },
  {
    "id":"terrain-caves","title":"Overworld — terreno & cavernas","subtitle":"Terralith + Tectonic + YUNG's Better Caves/Cave Biomes","type":"worldgen","color":"#65795d","difficulty":"Moderada","risk":"Médio","phase":"Início","equivalent":"pré-Nether","complexity":"Simples","confidence":"Alta","intro":"O terreno do mundo já nasce diferente. Não existe 'ativar Terralith': o guia serve para lembrar que relevo e cavernas maiores mudam navegação, queda e recuperação.",
    "sections":[["Superfície","Terralith amplia biomas usando blocos vanilla; Tectonic altera relevo e escala. Use mapas/waypoints porque acidentes geográficos deixam rotas menos óbvias."],["Subsolo","Better Caves/Cave Biomes aumentam volume e variedade. Escudo, balde d'água, blocos e marcação de rota valem mais do que levar um stack extra de minério."]],
    "craftings":[{"title":"Craftings","confidence":"Alta","body":"Worldgen puro: não existe receita de entrada."}],
    "checklist":[["terrain-biomes","Explorar três biomas/terrenos novos","Início"],["terrain-cave","Completar uma expedição longa em caverna reformulada","Início"]],"sources":[["Terralith","https://modrinth.com/mod/terralith"],["Tectonic","https://modrinth.com/mod/tectonic"]]
  },
  {
    "id":"piglin-proliferation","title":"Piglin Proliferation","subtitle":"novos nichos de piglins no Nether","type":"mobs / Nether","color":"#9b624b","difficulty":"Difícil","risk":"Alto","phase":"Intermediário","equivalent":"Nether-pré-Fortress","complexity":"Moderada","confidence":"Alta","intro":"O Nether fica menos previsível porque os piglins ganham variantes/nichos. Ouro ainda importa, mas não assuma que todo encontro se comporta igual ao piglin vanilla.",
    "sections":[["Primeira fase do Nether","Use pelo menos uma peça de ouro, escudo e Fire Resistance quando possível. Observe antes de atacar: agressão em grupo escala rápido."],["Bastions e encontros","As novas variantes mudam a leitura de grupos e funções. Trate como expansão do ecossistema piglin, não como boss line."]],
    "craftings":[{"title":"Craftings","confidence":"Alta","body":"Nenhum item de crafting é gate para o sistema; os mobs entram naturalmente no Nether."}],
    "checklist":[["piglin-see","Encontrar pelo menos duas variantes novas","Intermediário"],["piglin-bastion","Explorar um Bastion com o mod ativo","Intermediário"],["piglin-mechanics","Aprender uma mecânica específica de variante sem morrer para descobrir","Intermediário"]],"sources":[["Piglin Proliferation","https://modrinth.com/mod/piglin-proliferation/version/2.0.15"]]
  },
  {
    "id":"quark","title":"Quark","subtitle":"Quark + Quark Oddities","type":"vanilla+ / utilidade","color":"#6a6f86","difficulty":"Tranquilo","risk":"Baixo","phase":"Início","equivalent":"pré-Nether","complexity":"Moderada","confidence":"Alta","intro":"Quark é uma coleção de pequenas melhorias. A regra do guia é simples: usar quando resolver algo, não inventar uma campanha para um mod que deliberadamente é modular.",
    "sections":[["Quark base","Construção, decoração, QoL, mobs e pequenas mecânicas entram ao longo do jogo. O valor está em descobrir recursos e incorporá-los à base."],["Oddities","Oddities adiciona sistemas mais 'construíveis' ao redor do Quark. Ainda assim, não é gate de progressão e pode ser adotado conforme necessidade."],["Configuração","Quark é altamente modular. Se uma feature não aparecer, confirme se está habilitada antes de assumir conflito com outro mod."]],
    "craftings":[{"title":"Receitas","confidence":"Média-alta","body":"Quark tem muitas receitas pequenas e contextuais. Não existe uma receita central. Use a documentação/JEI por item específico, com confiança indicada quando entrar no guia."}],
    "checklist":[["quark-feature","Usar uma feature de Quark na base","Início"],["quark-build","Usar blocos Quark numa build","Início"],["quark-oddity","Testar uma mecânica de Quark Oddities","Intermediário"]],"sources":[["Quark","https://www.curseforge.com/minecraft/mc-mods/quark"],["Quark Oddities","https://www.curseforge.com/minecraft/mc-mods/quark-oddities"]]
  },
  {
    "id":"relics-artifacts","title":"Relíquias & Artefatos","subtitle":"Relics + Artifacts + More Relics + Reliquified add-ons","type":"loot / equipamento","color":"#806340","difficulty":"Moderada","risk":"Médio","phase":"Intermediário → Pós-jogo","equivalent":"Nether-pré-Fortress → endgame","complexity":"Moderada","confidence":"Alta","intro":"Esta entrada cresce junto da exploração. Artifacts entrega tesouros; Relics tem habilidades/leveling/research; addons adicionam novas peças, inclusive 7 relics temáticas obtidas de bosses da Twilight Forest.",
    "sections":[["Encontrar e testar","Não venda/descarte por aparência. Equipe em Curios, leia efeitos e compare duplicatas antes de decidir o que entra no loadout."],["Relics: evolução","Relics 0.12.8 possui habilidades, experiência e research. O próprio item indica formas de ganhar XP; algumas pesquisas/desbloqueios são individuais."],["Artifacts","Artifacts são tesouros de exploração e podem aparecer em loot/mimics/estruturas conforme a configuração. Não existe uma árvore de craft obrigatória."],["Twilight Forest","Reliquified Twilight Forest adiciona 7 relics temáticas obtidas ao derrotar bosses da dimensão. Elas entram naturalmente quando a campanha Twilight começa."],["Dream Relics","Continua fora do guia: <strong>a conferir</strong>, como já aprovado. Não pesquisar nem transformar em gate."]],
    "craftings":[{"title":"Relics/Artifacts","confidence":"Alta","body":"A maioria dos itens desta entrada é obtida por loot/bosses e evolui por uso/research, não por uma receita central."},{"title":"Reliquified Twilight Forest","confidence":"Alta","body":"As 7 relics são obtidas de bosses da Twilight Forest; não são tratadas como crafts."}],
    "checklist":[["relic-first","Obter e equipar uma relíquia/artefato","Intermediário"],["relic-level","Evoluir uma Relic por uso","Intermediário"],["relic-research","Completar uma pesquisa/desbloqueio de habilidade","Avançado"],["relic-twilight","Obter uma Relic de boss da Twilight Forest","Avançado"],["relic-loadout","Montar dois loadouts diferentes para situações distintas","Pós-jogo"]],"sources":[["Relics 0.12.8","https://modrinth.com/mod/relics-mod/version/0.12.8"],["Artifacts","https://www.curseforge.com/minecraft/mc-mods/artifacts"],["Reliquified Twilight Forest","https://www.curseforge.com/minecraft/mc-mods/reliquified-twilight-forest"]]
  }
];
