export const lote3Part4 = [
  {
    "id":"survival","title":"Sobrevivência — clima, estações & sede","subtitle":"Cold Sweat + Serene Seasons + Thirst Was Reclaimed + integrações","type":"sobrevivência","color":"#537184","difficulty":"Moderada","risk":"Médio","phase":"Início → Intermediário","equivalent":"pré-Nether","complexity":"Moderada","confidence":"Alta","intro":"Este grupo altera o loop básico: temperatura, estação e sede passam a importar juntos. O objetivo é criar hábitos cedo para que a dificuldade seja interessante, não burocrática.",
    "sections":[["Sede","Thirst Was Reclaimed adiciona sede e pureza da água. Água de fontes diferentes pode ter graus de pureza; comidas/bebidas e integrações restauram sede."],["Canteens","Thirst Canteen armazena água. Use como item padrão de viagem para parar de depender de garrafas soltas."],["Temperatura","Cold Sweat exige resposta ao ambiente: bioma, dimensão, armadura e fontes térmicas. Faça equipamento/isolamento conforme a viagem, não uma roupa universal."],["Estações","Serene Seasons altera estação e fertilidade de crops. Organize plantio e estoque para não depender de uma safra fora de época."],["Integrações úteis","Farmer's Delight pode purificar água no Cooking Pot e refeições ajudam a sede; Supplementaries preserva pureza em Jars/Goblets/Faucets; Seasonal Integration conecta mods às estações."]],
    "craftings":[{"title":"Purificação de água","confidence":"Alta","body":"Cooking Pot do Farmer's Delight pode purificar water bottles para grau Pure na integração 1.21.1. É processo de integração, não uma grade 3×3."},{"title":"Canteen","confidence":"Média","body":"O addon confirma canteens que armazenam água; receita exata varia por versão/material e não é reproduzida sem recipe data."},{"title":"Cold Sweat gear","confidence":"Média","body":"Cold Sweat possui itens/isolamento próprios. Use receitas por item no JEI somente quando a documentação daquele item não fornecer a grade."}],
    "checklist":[["surv-water","Garantir uma fonte de água confiável/purificada","Início"],["surv-canteen","Fazer e carregar uma canteen","Início"],["surv-temp","Montar um kit para frio ou calor extremo","Intermediário"],["surv-season","Organizar plantio pensando na estação","Início"],["surv-integration","Usar Farmer's Delight ou Supplementaries com o sistema de sede","Intermediário"]],"sources":[["Cold Sweat","https://www.curseforge.com/minecraft/mc-mods/cold-sweat"],["Serene Seasons","https://www.curseforge.com/minecraft/mc-mods/serene-seasons"],["Thirst Was Reclaimed","https://www.curseforge.com/minecraft/mc-mods/thirst-was-reclaimed"],["Thirst Canteen","https://modrinth.com/mod/thirst-canteen"]]
  },
  {
    "id":"spider-overhaul","title":"Spider Overhaul","subtitle":"aranhas, estruturas, itens, armas e comida","type":"mobs / combate","color":"#655247","difficulty":"Difícil","risk":"Médio","phase":"Intermediário","equivalent":"Nether-pré-Fortress","complexity":"Moderada","confidence":"Média","intro":"Este mod ficou com peso próprio porque adiciona mais do que aparência: mobs, estruturas, itens/armas e comida. A progressão é aprender os encontros sem fingir uma cadeia de bosses que a página do arquivo não documenta.",
    "sections":[["Exploração","Cavernas/noite deixam de ter 'só spider vanilla'. Leve escudo, ranged e rota de fuga em terreno com teias/veneno."],["Estruturas e loot","Explore as estruturas próprias quando aparecerem e trate armas/comidas como recompensa de conteúdo, não como gate."],["Confiança","A existência de mobs/estruturas/itens é confirmada para a versão do pack; uma sequência rígida não é. O guia permanece paralelo."]],
    "craftings":[{"title":"Receitas próprias","confidence":"Baixa-conferir","body":"O mod adiciona itens/armas/comida, mas a página pública da versão não fornece recipes suficientes para reproduzir grades. Conferir JEI apenas para o item que vocês decidirem produzir."}],
    "checklist":[["spider-var","Encontrar uma nova variante/mecânica de aranha","Intermediário"],["spider-structure","Explorar uma estrutura do Spider Overhaul","Intermediário"],["spider-loot","Obter um item/arma/comida própria do mod","Intermediário"]],"sources":[["Spider Overhaul","https://www.curseforge.com/minecraft/mc-mods/spider-overhaul"]]
  },
  {
    "id":"mob-variants","title":"Variações de mobs vanilla","subtitle":"Creeper Overhaul + Enderman Overhaul + Enhanced Mob Variants + Variants&Ventures","type":"mobs / variações","color":"#596d55","difficulty":"Moderada","risk":"Médio","phase":"Início","equivalent":"pré-Nether","complexity":"Simples","confidence":"Alta","intro":"Este é o grupo que deliberadamente ficou junto: variantes de mobs vanilla com mudanças visuais/comportamentais leves. O objetivo é aprender a reconhecer diferenças sem tratá-las como quatro campanhas.",
    "sections":[["Creepers","Creeper Overhaul distribui variantes por ambiente. A regra continua: espaço, som e escudo salvam mais inventário que confiança excessiva."],["Endermen","Enderman Overhaul amplia variantes/ambientes. Observe antes de assumir que todo enderman reage e luta igual ao vanilla."],["Outras variantes","Enhanced Mob Variants e Variants&Ventures ampliam o bestiário vanilla. Não existe boss/gate no grupo."]],
    "craftings":[{"title":"Craftings","confidence":"Alta","body":"Este grupo é centrado em mobs; não existe receita central obrigatória."}],
    "checklist":[["variants-creeper","Encontrar três variantes de creeper","Início"],["variants-enderman","Encontrar três variantes de enderman","Intermediário"],["variants-other","Encontrar cinco variantes de outros mobs","Intermediário"]],"sources":[["Creeper Overhaul","https://www.curseforge.com/minecraft/mc-mods/creeper-overhaul"],["Enderman Overhaul","https://www.curseforge.com/minecraft/mc-mods/enderman-overhaul"],["Variants&Ventures","https://github.com/Faboslav/variants-and-ventures"]]
  },
  {
    "id":"waystones","title":"Waystones","subtitle":"rede de viagem + teleport de pets","type":"transporte","color":"#6e557c","difficulty":"Tranquilo","risk":"Baixo","phase":"Início","equivalent":"pré-Nether","complexity":"Simples","confidence":"Alta","intro":"Waystones é infraestrutura de retorno. Ative cedo a base e pontos de interesse; o valor cresce conforme o mundo fica multidimensional.",
    "sections":[["Primeira rede","Ative a primeira Waystone e dê nomes úteis. Base, vilas, portais e dungeons distantes merecem pontos claros."],["Pets","O addon Waystones Teleport Pets existe no grupo aprovado. Teste transporte com um pet antes de depender dele numa viagem longa."],["Custo/regras","Warp cost/cooldown/requirements são configuráveis. O guia não assume que todo warp é gratuito; a interface do servidor é a fonte final das regras ativas."]],
    "craftings":[{"title":"Waystones e scrolls","confidence":"Média","body":"O mod permite encontrar/craftar Waystones e craftar magical scrolls. Como o pack pode alterar recipes/config e há várias variantes, não reproduzimos uma grade única sem recipe data da versão instalada."},{"title":"Mossy Waystone","confidence":"Alta","body":"A série 1.21.1 documenta uma receita a partir de Moss Blocks, mas a grade exata não é necessária para o fluxo principal."}],
    "checklist":[["way-base","Ativar/nomear a Waystone da base","Início"],["way-village","Registrar uma vila ou ponto útil","Início"],["way-dimension","Registrar um ponto de acesso dimensional","Intermediário"],["way-pet","Testar teleport com um pet","Intermediário"]],"sources":[["Waystones","https://www.curseforge.com/minecraft/mc-mods/waystones"]]
  },
  {
    "id":"alex-mobs","title":"Alex's Mobs Continued","subtitle":"fauna utilitária + Void Worm","type":"mobs / boss","color":"#7b6b52","difficulty":"Difícil","risk":"Alto","phase":"Intermediário → Pós-jogo","equivalent":"Nether-pré-Fortress → pós-Dragão","complexity":"Complexa","confidence":"Média-alta","intro":"Alex's Mobs tem dezenas de criaturas com materiais e comportamentos próprios. O guia separa a fauna do grande encontro formal: o Void Worm no End.",
    "sections":[["Fauna primeiro","Use Animal Dictionary/observação para aprender neutros e utilidade antes de atacar. Algumas criaturas são muito mais perigosas que um mob vanilla de tamanho parecido."],["Materiais","Colete materiais dos encontros que vocês realmente usarem. Não transforme o bestiário numa checklist de extermínio."],["Mysterious Worm","A linha do boss passa por <strong>Crimson Mosquito Larva em um Capsid</strong>, gerando Mysterious Worm. O port 1.21.1 confirma que Void Worm é summonable via esse item."],["Void Worm","No End, jogue o Mysterious Worm no void para invocar o Void Worm. Mire na cabeça: atingir segmentos do corpo repetidamente pode dividir o worm e criar mais worms. O boss base tem 160 HP por configuração padrão."],["Depois","Void Worm Eye/Mandibles entram na linha do Dimensional Carver. É conteúdo pós-Dragão na curva sugerida."]],
    "craftings":[{"title":"Mysterious Worm","confidence":"Média-alta","body":"Obtido colocando Crimson Mosquito Larva em um Capsid; é transformação/interação, não crafting 3×3."},{"title":"Dimensional Carver","confidence":"Média","body":"Usa drops do Void Worm. A existência/uso é confirmada; grade exata não reproduzida sem recipe data do port Continued."}],
    "checklist":[["alex-fauna","Interagir com cinco espécies sem simplesmente matar tudo","Intermediário"],["alex-material","Obter três materiais utilitários de mobs","Intermediário"],["alex-worm-item","Criar/obter Mysterious Worm","Pós-jogo"],["alex-worm-boss","Invocar e derrotar Void Worm","Pós-jogo"],["alex-carver","Produzir/testar Dimensional Carver","Pós-jogo"]],"sources":[["Alex's Mobs Continued","https://www.curseforge.com/minecraft/mc-mods/alexs-mobs-continued/files/8615110"],["Void Worm — referência de comportamento","https://alexs-mobs-unofficial.fandom.com/wiki/Void_Worm"]]
  }
];
