"""Build additive, reviewable content lots; never reads/writes player state."""
import json
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
BASE=ROOT.parent/'progressao-helpers'
payload=json.loads((ROOT/'data/progression-baseline-2026-10-10.json').read_text())
items=payload['items']
by={x['order']:x for x in items}
fields=['order','entry','mods','title','type','equipment','required','soft','risk','unprepared','complexity','reversibility','vanilla','phase','dependency','confidence','source','notes']
EDITORIAL='Fase, risco e kit são calibração editorial de conforto, não requisitos impostos pelo mod. Configurações efetivas do save e combate combinado no pack não foram testados. Marco opcional; sem gate de boss para outras trilhas.'
def add(n,entry,mods,title,type,equipment,required,soft,risk,unprepared,complexity,reversibility,vanilla,phase,dependency,confidence,source,notes='',gate=None):
    assert n not in by, f'ID ocupado: {n}'
    d=dict(zip(fields,[n,entry,mods,title,type,equipment,required,soft,risk,unprepared,complexity,reversibility,vanilla,phase,dependency,confidence,source,notes+' '+EDITORIAL]))
    d['id']=f'progression:{n}'
    d['icone']='/icons/structure.svg' if 'Estrutura' in type or 'Expedição' in type else '/icons/item.svg'
    if gate:d['gate']=gate
    by[n]=d;items.append(d)
def steps(n,rows):
    assert not by[n].get('subitens'),f'Subitens existentes em {n}'
    by[n]['subitens']=[]
    for row in rows:
        slug,title,*options=row
        s={'id':f'progression:{n}:{slug}','title':title,'phase':by[n]['phase'],'confidence':'Alta nos recursos auditados; preparo editorial','icone':'/icons/item.svg'}
        if options and options[0]:s['bestiaryId']=options[0]
        if len(options)>1:s['confidence']=options[1]
        if title.startswith('Derrotar '):s.update(trophy=True,icone='/icons/boss.svg')
        by[n]['subitens'].append(s)
def lot(number,changed):
    items.sort(key=lambda x:x['order'])
    patch=[by[n] for n in changed]
    (ROOT/'data'/f'progression-lot-{number}.json').write_text(json.dumps(patch,ensure_ascii=False,indent=2)+'\n')
    (BASE/f'payload-lot-{number}.json').write_text(json.dumps(payload,ensure_ascii=False,indent=2)+'\n')

add(142,'Relíquias & Artefatos','Relics, More Relics, Reliquified Twilight Forest, reliquified_artifacts','Desenvolver uma relíquia com experiência e uma habilidade útil','Equipamento / especialização','Sem tier de armadura obrigatório; uma relíquia do sistema Relics','Possuir uma relíquia com experiência/habilidades do Relics; não se aplica a todo Artifact','Ler a interface e escolher uma habilidade que ajude nas atividades atuais; testar perto da base','Baixo','Investir em um efeito que não combina com o uso atual custa tempo; obter experiência pode expor ao risco da atividade escolhida.','Moderada','Alta — pode trocar a relíquia; investimento e estatísticas não têm reset presumido','Especializar equipamento encantado','Intermediário','Depois de obter uma relíquia em #140; requisito é o item, não marcar #140 nem vencer um chefe.','Alta para o sistema; Média para calibração','https://www.curseforge.com/minecraft/mc-mods/relics-mod','Relics 0.12.8: experiência, estatísticas aleatórias e habilidades progressivas. Não exige nível máximo, conjunto completo ou quantidade inventada.')
steps(142,[('inspect','Escolher uma relíquia Relics e ler sua habilidade e condição de experiência'),('experience','Ganhar experiência usando a condição indicada pela própria relíquia'),('ability','Aplicar uma melhoria disponível e testar a habilidade escolhida')])
add(145,'Better Archeology','Better Archeology','Fazer uma escavação e identificar o primeiro artefato','Arqueologia / utilidade','Escova; ferramentas básicas; ferro/escudo se o sítio estiver ocupado','Encontrar materiais escováveis do mod; Unidentified Artifact e Archeology Table para identificação','Iluminar e preservar blocos suspeitos; consultar JEI para as receitas da build instalada','Baixo','Quebrar blocos escováveis pode perder o achado; estruturas escuras podem conter ameaças comuns.','Moderada','Alta — pode voltar e procurar outro sítio; achados destruídos não são recuperáveis','Arqueologia de Trail Ruins','Início','Trilha paralela — sem boss gate; identificação vem depois da escavação.','Alta para 1.3.8; Média para preparo','https://www.curseforge.com/minecraft/mc-mods/better-archeology/files/8577242\nhttps://www.curseforge.com/minecraft/mc-mods/better-archeology','Build instalada 1.3.8, não a 1.3.9 posterior. O changelog confirma identificação via receitas da Archeology Table. Não exige todo fóssil/artefato.')
steps(145,[('excavation','Escovar um sítio com Suspicious Dirt ou Suspicious Red Sand'),('artifact','Obter um Unidentified Artifact pela arqueologia do mod'),('identify','Identificar o artefato na Archeology Table')])
add(175,'Golems — utilitários, defesa & automação','Straw Golem Updated, Golem Overhaul','Colocar um golem utilitário em uma função real na base','Utilidade / automação','Sem tier de armadura obrigatório; materiais do golem escolhido','Criar ou encontrar um golem do grupo; plantação e recipiente para a trilha Straw Golem','Começar por uma plantação pequena e protegida; manter alimento e reparos conforme o tipo','Baixo','Golems vulneráveis podem morrer ou parar de trabalhar por falta de manutenção; não substituem defesa automática garantida.','Moderada','Alta — projeto da base ajustável; morte consome a entidade e seus materiais','Colheita e proteção de lavoura / Iron Golem','Início','Trilha paralela — ordem indiferente; não exige Create, Nether ou boss.','Alta para funções; Média para preparo','https://modrinth.com/mod/straw-golem-rebaled-updated\nhttps://modrinth.com/mod/golem-overhaul\nhttps://modrinth.com/mod/golem-overhaul/gallery','Straw Golem 2.2.2: colheita, replantio e entrega configuráveis; fome/duração exigem manutenção. Golem Overhaul 1.1.1 oferece nove tipos: escolher um uso basta; não obriga criar nove. #175 livre nas duas fontes em 10/10.')
steps(175,[('choose','Escolher Straw Golem para colheita ou um tipo utilitário do Golem Overhaul'),('deploy','Criar/encontrar o golem escolhido e preparar sua área de trabalho'),('function','Confirmar uma entrega de colheita ou a função específica do golem escolhido'),('upkeep','Preparar alimento/reparo e proteger o golem de ameaças')])
steps(190,[('iceologer','Encontrar a Iceologer Cabin e enfrentar o Iceologer','friendsfoes-iceologer'),('illusioner','Enfrentar o Illusioner e distinguir suas ilusões','friendsfoes-illusioner'),('wildfire','Localizar a Citadel do Nether e enfrentar Wildfire','friendsfoes-wildfire')])
steps(200,[('desert','Reconhecer Desert Spider e sua rajada de espinhos','spideroverhaul-desert_spider'),('cavern','Enfrentar Cavern Spider e aprender a restrição Webbed','spideroverhaul-cavern_spider'),('ice','Reconhecer Ice Spider e responder ao efeito Icy','spideroverhaul-ice_spider')])
by[200]['notes']+=' Detalhamento adicional: conclusão histórica do marco preservada; novos subitens começam desmarcados. Os encontros formam uma amostra prática, não uma coleção de todas as variantes.'
steps(210,[('dictionary','Consultar o Animal Dictionary para um encontro do Overworld'),('roadrunner','Obter Roadrunner Feather e conferir sua utilidade no Bestiário','alexsmobs-roadrunner'),('nether','Reconhecer Crimson Mosquito no Nether e preparar retirada','alexsmobs-crimson-mosquito')])
steps(220,[('basher','Enfrentar Basher sem insistir contra seu escudo','illagerinvasion-basher'),('sorcerer','Enfrentar Sorcerer e evitar sua magia de área','illagerinvasion-sorcerer'),('invoker','Enfrentar Invoker e obter Hallowed Gem para a linha de Imbuing Table','illagerinvasion-invoker')])
steps(230,[('alchemist','Reconhecer Piglin Alchemist e sua assistência por poções','piglinproliferation-piglin_alchemist'),('barter','Fazer uma troca com Piglin Alchemist sem provocar o grupo','piglinproliferation-piglin_alchemist'),('traveler','Encontrar Piglin Traveler e conhecer suas trocas','piglinproliferation-piglin_traveler')])
lot(1,[142,145,175,190,200,210,220,230])

DNT='https://modrinth.com/datapack/dungeons-and-taverns/version/v4.4.4\nhttps://cdn.modrinth.com/data/tpehi7ww/versions/BYUUUeZA/dungeons-and-taverns-v4.4.4.jar'
add(245,'Masmorras, estruturas & assentamentos','Dungeons and Taverns','Explorar uma dungeon do Overworld de Dungeons and Taverns','Estrutura / dungeon','Ferro completo, escudo, arco, iluminação e blocos','Localizar uma estrutura D&T do Overworld','Começar por um complexo menor; marcar saídas e conferir armadilhas antes de abrir salas','Médio','Salas hostis e armadilhas prolongam a exploração; perder a saída dificulta recuperar o inventário.','Moderada','Alta antes de engajar; média dentro do complexo','Dungeon / Pillager Outpost ampliado','Intermediário','Trilha paralela — não depende das tavernas de #240 nem dos D&T Nether/End.','Alta para estruturas 4.4.4; Média para dificuldade',DNT,'Worldgen do JAR confirma Creeping Crypt, Illager Hideout e outros complexos do Overworld; completar uma dungeon escolhida basta. Não obriga todos os Shrines ou vaults.')
steps(245,[('locate','Encontrar Creeping Crypt ou Illager Hideout no Overworld'),('rooms','Explorar as salas hostis da estrutura escolhida com a saída marcada'),('finish','Concluir a incursão à Creeping Crypt/Illager Hideout e levar os achados à base')])
add(265,'Masmorras, estruturas & assentamentos','When Dungeons Arise','Fazer uma expedição a uma mega-dungeon do When Dungeons Arise','Estrutura / mega-dungeon','Diamante encantado, escudo, ranged, cura, blocos e retorno próximo','Encontrar Shiraz Palace, Keep Kayra ou outra megaestrutura hostil do WDA','Reconhecer acessos e dividir a limpeza em sessões; não levar todos os itens valiosos','Alto','Combate prolongado, spawners, corredores e quedas podem gastar o kit antes de alcançar a saída.','Complexa','Média — é possível recuar, mas a recuperação pode exigir nova incursão','Woodland Mansion prolongada','Avançado','Trilha paralela — #260 ajuda a aprender o mod, mas não é chave nem requisito de geração.','Alta para estruturas; Média para calibre do pack','https://www.curseforge.com/minecraft/mc-mods/when-dungeons-arise','2.1.68: palácios/fortalezas extensos, inimigos e loot próprios. Mega-dungeon é um recorte editorial por escala, não tier de desbloqueio registrado pelo mod.')
steps(265,[('target','Escolher Shiraz Palace ou Keep Kayra e marcar um retorno próximo'),('entry','Conquistar um acesso seguro e o primeiro setor da mega-dungeon'),('depth','Explorar os setores internos do palácio/fortaleza em sessões'),('extract','Concluir a expedição escolhida e retirar o loot pela rota marcada')])
add(275,'Masmorras, estruturas & assentamentos','Integrated Seven Seas','Abordar e explorar um navio do Integrated Seven Seas','Expedição marítima / dungeon','Ferro completo, escudo, ranged, barco e blocos; diamante para navios mais difíceis','Localizar um navio do ISS em oceano profundo','Inspecionar o convés à distância, deixar barco/retorno seguro e explorar o interior','Alto','Mais inimigos no convés/interiores e uma fuga sobre água podem transformar a abordagem em cerco ou afogamento.','Moderada','Média — recuar ao barco é possível se a saída continuar livre','Navio hostil / Pillager Outpost sobre água','Intermediário','Trilha paralela — independente de Elder Guardians, monumentos e #270.','Alta para design 1.1.0; Média para dificuldade','https://www.curseforge.com/minecraft/mc-mods/integrated-seven-seas\nhttps://www.curseforge.com/minecraft/mc-mods/integrated-seven-seas/files/all','ISS 1.1.0: navios dos Seven Seas reestruturados, mais inimigos e loot rebalanceado para começo de jogo. Victory Frigate não faz parte; respiração aquática não é gate para um navio de superfície.')
steps(275,[('ship','Localizar um navio do ISS no oceano profundo'),('board','Abordar o convés sem perder o acesso ao barco'),('interior','Explorar o interior reformulado e seus encontros'),('return','Retirar os achados do navio e voltar com segurança')])
add(285,'Masmorras, estruturas & assentamentos','Dungeons and Taverns','Explorar Nether Keep ou Piglin Donjon do Dungeons and Taverns','Estrutura / Nether','Diamante, escudo, ranged, comida, blocos e kit contra fogo','Acesso ao Nether e localizar uma estrutura D&T da dimensão','Marcar saída e portal; resistência ao fogo recomendada; observar piglins antes de provocar','Alto','Grupos hostis e lava tornam retirada e recuperação do inventário mais difíceis.','Complexa','Média — retorno depende do acesso e das rotas em terreno do Nether','Bastion Remnant / Nether Fortress','Avançado','Trilha paralela — independente de #245 e das fortalezas YUNG de #280.','Alta para worldgen 4.4.4; Média para combate',DNT,'O JAR registra nether_keep e piglin_donjon com tags de biomas do Nether; não presumir que loot ou entrada exigem um boss anterior.')
steps(285,[('nether-target','Encontrar Nether Keep ou Piglin Donjon'),('route','Marcar a conexão segura da estrutura com seu portal'),('complex','Explorar o complexo escolhido e retirar os achados')])
add(845,'Masmorras, estruturas & assentamentos','Dungeons and Taverns','Explorar End Castle ou uma estrutura externa do Dungeons and Taverns','Estrutura / End','Diamante fortemente encantado, ranged, blocos, pérolas e proteção contra quedas','Acesso ao End; localizar End Castle, End Lighthouse ou End Ship','Para ilhas externas, usar a rota pós-Dragão; levar Slow Falling e backup','Alto','Quedas no vazio podem eliminar os itens; a recuperação depende de alcançar a estrutura novamente.','Complexa','Baixa sobre o vazio; média dentro de rota protegida','End City / End Ship','Pós-jogo','Trilha paralela depois do acesso #830; pós-Dragão é conforto logístico, não gate inventado do End Castle.','Alta para worldgen 4.4.4; Média para combate',DNT,'end_castle usa collections/end; end_ship usa outer_end; end_lighthouse usa has_structure/end_city. Não impor Ender Dragon como requisito universal da geração.',gate={'confirmed':True,'depends_on':['progression:830'],'note':'Acesso à dimensão; nenhuma ordem rígida entre dungeons.'})
steps(845,[('end-target','Localizar End Castle, End Lighthouse ou End Ship do D&T'),('approach','Construir uma chegada e uma saída protegidas contra o vazio'),('end-rooms','Explorar a estrutura do End escolhida e retirar seus achados')])
for row in json.loads((ROOT/'data/progression-pillage-approved-2026-10-10.json').read_text()):
    if row[0] in [235,355]:
        n=row[0];assert n not in by
        d=dict(zip(fields,row));d['id']=f'progression:{n}';d['icone']='/icons/structure.svg';by[n]=d;items.append(d)
steps(235,[('camp','Localizar um Pillager Camp e observar os acessos'),('raiders','Enfrentar os raiders do acampamento com uma rota de retirada'),('loot','Explorar as tendas do Pillager Camp e retirar os achados')])
steps(355,[('bastille','Localizar uma Bastille e marcar o retorno'),('courtyard','Conquistar um acesso e explorar o pátio da Bastille'),('interior','Explorar os interiores hostis e retirar os achados da fortaleza')])
steps(250,[('mineshaft','Explorar uma YUNG’s Better Mineshaft com rota iluminada'),('dungeon','Concluir uma dungeon reformulada pelo YUNG’s Better Dungeons'),('desert','Explorar um Better Desert Temple verificando armadilhas'),('jungle','Resolver os acessos/armadilhas de um Better Jungle Temple'),('witch','Enfrentar o encontro de uma Better Witch Hut')])
by[260]['title']='Conhecer WDA por um complexo hostil menor antes das mega-dungeons'
by[260]['notes']='Estruturas menores e aprendizado do mod; mega-dungeons são o recorte de #265. Isso não constitui gate técnico entre os dois marcos.'
steps(260,[('recon','Reconhecer Illager Campsite ou Illager Windmill'),('smaller','Explorar o acampamento/moinho escolhido e seus encontros'),('maps','Consultar os mapas de exploração de uma estrutura passiva do WDA')])
by[270]['mods']="YUNG's Better Ocean Monuments";by[270]['title']='Explorar YUNG’s Better Ocean Monument e vencer seus Elder Guardians'
by[270]['source']='https://www.curseforge.com/projects/1015115'
by[270]['notes']='ISS agora tem #275: navios de superfície não herdam o gate aquático do monumento. ID e progresso de #270 preservados.'
steps(270,[('monument','Localizar um Better Ocean Monument e marcar acesso ao ar'),('guardians','Enfrentar os Elder Guardians do monumento com respiração preparada'),('sponge','Explorar as salas do monumento e retirar os achados antes de acabar o ar')])
steps(600,[('graveyard','Explorar um Graveyard e reconhecer Ghoul/Revenant','graveyard-ghoul'),('crypt','Fazer uma incursão a uma Crypt sem iniciar o ritual do Lich'),('ruins','Localizar uma Ruins com fragmento do Ominous Bone Staff')])
steps(610,[('upper','Obter o fragmento superior do Ominous Bone Staff em Ruins'),('middle','Obter o fragmento central do Ominous Bone Staff em Ruins'),('lower','Obter o fragmento inferior do Ominous Bone Staff em Ruins'),('blood','Preparar Bone Dagger e encher Vial of Blood conforme o ritual'),('prison','Localizar Lich Prison e preparar o acesso ao altar antes da noite')])
by[610]['source']+='\nhttps://www.curseforge.com/minecraft/mc-mods/the-graveyard-forge'
steps(760,[('sanctum','Explorar o Sanctum e seus cultistas','incendium-sanctum-cultist'),('reactor','Fazer uma incursão ao Nether Reactor'),('castle','Explorar Forbidden Castle com proteção contra fogo e saída marcada')])
lot(2,[235,245,250,260,265,270,275,285,355,600,610,760,845])

INC='https://github.com/Stardust-Labs-MC/Incendium/blob/fedbebcef160c47aca4e8bdfa82fc7473b7eabee/data/incendium/functions/hovering_inferno/summon.mcfunction\nhttps://www.stardustlabs.net/incendium'
add(765,'Incendium / Nether reformulado','Incendium','Invocar e derrotar Hovering Inferno no Infernal Altar','Chefe customizado','Diamante fortemente encantado/netherite, ranged, cura, resistência ao fogo e retorno seguro','Acesso ao Nether, Infernal Altar e Nether Star para ativar o encontro','Reconhecer a arena antes de consumir a estrela; levar reserva de cura e equipamento','Severo','O encontro de Blaze customizado tem muita vida e ataques próprios; fogo, knockback e terreno tornam a recuperação cara.','Complexa','Alta antes da invocação; baixa durante o combate','Wither / boss opcional pós-Dragão','Pós-jogo','Trilha paralela — não exige limpar todas as estruturas de #760; Nether Star é item requerido, não sequência de bosses criada pelo site.','Alta para função oficial; Média para calibração',INC,'Incendium 5.4.4 usa minecraft:blaze customizado, não entidade incendium:*; o código de summon consome a Nether Star. Não inventar percentuais de fases ou loot não auditado.')
steps(765,[('altar','Localizar Infernal Altar e reconhecer a arena'),('nether-star','Reunir Nether Star e preparar o kit contra fogo'),('summon','Ativar o Infernal Altar com a Nether Star'),('inferno','Derrotar Hovering Inferno','incendium-hovering-inferno')])
MM='https://www.curseforge.com/minecraft/mc-mods/mowzies-mobs'
add(795,"Mowzie's Mobs","Mowzie's Mobs",'Completar o teste de Tongbi, o Sculptor','Desafio / Geomancy','Ferro/diamante para Bluffs; comida, mobilidade e preparo contra quedas','Earthrend Monastery, Tongbi disponível e Bluff Rod para iniciar o teste','Limpar os encontros no acesso e tentar o parkour sem provocar Tongbi; conferir regras da prova','Alto','Quedas e Bluffs atrapalham o percurso; atacar Tongbi troca a prova por combate e pode eliminar a oportunidade local.','Complexa','Média — novas tentativas dependem de recursos; matar o NPC é irreversível naquele encontro','Parkour de altura / desafio opcional de End City','Avançado','Trilha paralela — não exige Ferrous Wroughtnaut, Frostmaw ou Umvuthi.','Alta para prova/recompensa; Média para dificuldade',MM,'Mowzie’s Mobs 1.8.2: o objetivo é o teste e Earthrend Gauntlet. Não exige derrotar o NPC nem voar; não presume tempo/altura/configuração do pack.')
steps(795,[('monastery','Encontrar Earthrend Monastery e acessar o pátio de Tongbi','mowzies-mobs-sculptor'),('bluff-rod','Obter Bluff Rod dos Bluffs para iniciar o teste','mowzies-mobs-bluff'),('test','Iniciar e completar o percurso de parkour do Sculptor'),('gauntlet','Receber Earthrend Gauntlet pela conclusão da prova','mowzies-mobs-sculptor')])
steps(690,[('candy','Chegar a Candy Cavity e marcar uma saída'),('town','Explorar uma Gingerbread Town'),('licoroot','Reconhecer Licowitch Tower à distância sem iniciar sua limpeza')])
steps(720,[('brainiac','Enfrentar Brainiac nas Toxic Caves','alexscaves-brainiac'),('egg-materials','Reunir Tremorsaurus Egg, Tectonic Shard e Immortal Embryo para Tremorzilla Egg','alexscaves-luxtructosaurus'),('egg','Criar Tremorzilla Egg com os três componentes'),('hatch','Eclodir Tremorzilla Egg por explosão nuclear em área afastada da base','alexscaves-tremorzilla')])
by[720]['title']='Brainiac e criação de Tremorzilla — Toxic Caves'
by[720]['required']='Toxic Caves para Brainiac; Tremorsaurus Egg, Tectonic Shard e Immortal Embryo + explosão nuclear para eclosão de Tremorzilla Egg'
by[720]['dependency']='Brainiac não depende de outros chiefs. A receita de Tremorzilla usa recompensas de Luxtructosaurus (#700) e Hullbreaker (#710); não são gates para Brainiac.'
by[720]['source']+='\nhttps://alexscaves.wiki.gg/wiki/Tremorzilla_Egg\nhttps://alexscaves.wiki.gg/wiki/Nuclear_Bomb'
by[720]['notes']='Tremorzilla é uma trilha de criação/eclosão, não uma morte obrigatória. Não se afirma independência da receita em relação a Luxtructosaurus/Hullbreaker. Configuração efetiva do save a conferir.'
by[720]['subitens'][1]['bestiaryIds']=['alexscaves-luxtructosaurus','alexscaves-hullbreaker','alexscaves-tremorsaurus']
steps(730,[('ritual','Reconhecer o ritual de Underzealots com Gloomoth/Vesper','alexscaves-underzealot'),('watcher','Enfrentar Watcher produzido pelo ritual com Gloomoth','alexscaves-watcher'),('forsaken','Enfrentar Forsaken produzido pelo ritual com Vesper','alexscaves-forsaken'),('darkness','Obter Pure Darkness do Forsaken e conferir sua utilidade','alexscaves-forsaken')])
by[730]['source']+='\nhttps://alexscaves.wiki.gg/wiki/Underzealot\nhttps://alexscaves.wiki.gg/wiki/Forsaken'
steps(770,[('chamber','Localizar Wrought Chamber do Ferrous Wroughtnaut'),('weakness','Reconhecer a janela de vulnerabilidade do Wroughtnaut'),('defeat','Derrotar Ferrous Wroughtnaut','mowzies-mobs-ferrous-wroughtnaut'),('equipment','Obter Wrought Helm e Axe of a Thousand Metals','mowzies-mobs-ferrous-wroughtnaut')])
steps(780,[('snow','Localizar Frostmaw em região nevada'),('breath','Reconhecer o sopro congelante e preparar espaço de retirada'),('defeat','Derrotar Frostmaw','mowzies-mobs-frostmaw'),('crystal','Obter Ice Crystal do Frostmaw quando ele ainda guarda o cristal','mowzies-mobs-frostmaw')])
steps(790,[('grove','Localizar Umvuthana Grove e o trono de Umvuthi'),('sun','Reconhecer Sunstrikes e as invocações de Umvuthi'),('defeat','Derrotar Umvuthi','mowzies-mobs-umvuthi'),('visage','Obter Sol Visage e conferir seu uso com máscaras','mowzies-mobs-umvuthi')])
steps(800,[('worm','Preparar Mysterious Worm e chegar a uma borda segura do End'),('summon','Arremessar Mysterious Worm no vazio do End para invocar Void Worm'),('head','Reconhecer cabeça e segmentos; evitar dividir o Void Worm'),('defeat','Derrotar Void Worm','alexsmobs-void-worm'),('drops','Obter Void Worm Eye / Void Worm Mandible da entidade original','alexsmobs-void-worm')])
by[800]['notes']='Loot do Void Worm original difere dos segmentos/divisões; não presumir recompensa de cada divisão. ID e qualquer estado existente preservados.'
bosses={
900:('Soul Forge','Netherite Monstrosity','cataclysm-netherite_monstrosity','lava e investidas','Infernal Forge / Monstrous Horn'),
910:('Ruined Citadel','Ender Guardian','cataclysm-ender_guardian','ataques de área e quebra da arena','Gauntlet of Guard'),
920:('Ancient Factory','Harbinger','cataclysm-the_harbinger','mísseis/lasers e EMP Blocks da fábrica','Witherite Block'),
930:('Cursed Pyramid','Ancient Remnant','cataclysm-ancient_remnant','ataques de área na pirâmide','Sandstorm in a Bottle / Remnant Skull'),
940:('Sunken City','Leviathan','cataclysm-the_leviathan','mobilidade e respiração durante combate submerso','Tidal Claws / Abyssal Egg'),
950:('Acropolis','Scylla','cataclysm-scylla','mobilidade vertical e ataques do encontro','Essence of the Storm'),
960:('Frosted Prison','Maledictus','cataclysm-maledictus','alternância de armas e ataques próximos','Cursium Ingot'),
}
for n,(structure,boss,mob,mechanic,drops) in bosses.items():
    steps(n,[('structure',f'Localizar {structure} e marcar o retorno'),('arena',f'Acessar a arena de {boss} e confirmar a ativação na build do pack',None,'Média — ativação exata/configuração a conferir no pack'),('pattern',f'Aprender {mechanic} de {boss}'),('defeat',f'Derrotar {boss}',mob),('reward',f'Obter {drops} e conferir a utilidade no Bestiário',mob)])
    by[n]['subitens'][2]['confidence']='Média — padrões/ativação nesta build a conferir no pack'
    by[n]['notes']='Chefe solo em trilha paralela. Os nomes de estruturas e loot têm fontes; ativação exata e configurações desta build seguem explicitamente a conferir, sem inventar item de invocação ou percentuais de fase. Subitens novos não herdam marcação do pai.'
    by[n]['source']+='\nhttps://lendercataclysm.wiki.gg/\n'+f'https://lendercataclysm.wiki.gg/wiki/{boss.replace(" ","_")}'
by[980].update(transversal=True,type='Objetivo transversal / integração',title='Aplicar as integrações do Integrated Cataclysm durante as expedições aos bosses',required='Encontrar uma estrutura Cataclysm modificada pelo Integrated Cataclysm',dependency='Objetivo transversal: acompanha #900–970 conforme a estrutura escolhida; não depende de concluir todos os bosses e não cria uma campanha adicional.',notes='O ID #980 e seu histórico são preservados. Exibição junto às trilhas transversais, fora do fim da sequência de bosses. Equipamento/risco acompanham o encontro escolhido; não exige limpar todas as estruturas.',gate={'confirmed':False,'depends_on':[],'note':'Nenhum gate global depois dos bosses; disponibilidade depende da estrutura visitada.'})
lot(3,[690,720,730,765,770,780,790,795,800,900,910,920,930,940,950,960,980])
(ROOT/'data/progression-reconciliation-2026-10-10.json').write_text(json.dumps({'baselineIds':[x['id'] for x in json.loads((ROOT/'data/progression-baseline-2026-10-10.json').read_text())['items']],'newIds':[f'progression:{n}' for n in [142,145,175,235,245,265,275,285,355,765,795,845]],'notes':['No state-table DML. New children excluded from legacy backfill.','Pending advancements deliberately excluded.','All difficulty/gear suggestions are editorial, not mod gates.']},ensure_ascii=False,indent=2)+'\n')
print(json.dumps({'total':len(items),'subitems':sum(len(x.get('subitens',[])) for x in items),'new':12,'enriched':25}))
